(()=>{
  const $=s=>document.querySelector(s), content=$('#content');
  const state={user:null,current:'dashboard',rows:[],filtered:[],lookup:{},query:''};
  const mods=ModuleCatalog.modules;
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const initials=n=>(n||'RC').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
  const has=p=>!p||state.user?.permissions?.includes(p);
  const toast=(m,type='success')=>{const d=document.createElement('div');d.className=`toast ${type}`;d.textContent=m;$('#toastRoot').append(d);setTimeout(()=>d.remove(),3600)};
  const dateFmt=v=>{if(!v)return '—';const d=new Date(v);return isNaN(d)?esc(v):new Intl.DateTimeFormat('es-BO',{dateStyle:'medium'}).format(d)};
  const dateTimeFmt=v=>{if(!v)return '—';const d=new Date(v);return isNaN(d)?esc(v):new Intl.DateTimeFormat('es-BO',{dateStyle:'short',timeStyle:'short'}).format(d)};
  const money=v=>new Intl.NumberFormat('es-BO',{style:'currency',currency:'BOB',maximumFractionDigits:2}).format(Number(v||0));
  const human=s=>String(s??'').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/_/g,' ');

  async function boot(){
    try{state.user=await Api.get('/api/auth/me');await Api.csrf()}catch{location.href='index.html';return}
    $('#logoIcon').innerHTML=Icons.svg('car');$('#searchIcon').innerHTML=Icons.svg('search');$('#refreshBtn').innerHTML=Icons.svg('refresh');$('#notificationIcon').innerHTML=Icons.svg('bell');$('#menuBtn').innerHTML=Icons.svg('grid');
    const role=state.user.roles?.[0]||'Usuario';
    $('#userName').textContent=state.user.fullName;$('#profileName').textContent=state.user.fullName;$('#userRole').textContent=human(role);$('#avatar').textContent=initials(state.user.fullName);$('#profileAvatar').textContent=initials(state.user.fullName);
    buildNav();wireShell();await loadNotifications();route();
  }

  function buildNav(){
    $('#nav').innerHTML=ModuleCatalog.groups.map(g=>{const items=g.items.filter(k=>mods[k]&&has(mods[k].permission));if(!items.length)return '';return `<div class="nav-group"><span class="nav-label">${esc(g.label)}</span>${items.map(k=>`<button class="nav-item" data-module="${k}">${Icons.svg(mods[k].icon)}<span>${esc(mods[k].title)}</span></button>`).join('')}</div>`}).join('');
    $('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-module]');if(!b)return;location.hash=b.dataset.module;$('#sidebar').classList.remove('open')});
  }

  function wireShell(){
    window.addEventListener('hashchange',route);$('#refreshBtn').addEventListener('click',()=>loadModule(state.current,true));$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
    $('#profileBtn').addEventListener('click',()=>$('#profileMenu').classList.toggle('hidden'));$('#notificationBtn').addEventListener('click',()=>$('#notificationPanel').classList.toggle('hidden'));
    $('#logoutBtn').addEventListener('click',async()=>{try{await Api.post('/api/auth/logout',{})}catch{}location.href='index.html'});
    $('#changePasswordBtn').addEventListener('click',showChangePassword);
    if($('#backupExportBtn'))$('#backupExportBtn').addEventListener('click',()=>{try{RentCarStore.downloadBackup();toast('Respaldo JSON generado.')}catch(e){toast(e.message,'error')}});
    if($('#backupImportBtn'))$('#backupImportBtn').addEventListener('click',()=>$('#backupFileInput').click());
    if($('#backupFileInput'))$('#backupFileInput').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{await RentCarStore.importBackupFile(f);alert('Respaldo importado. Por seguridad debes iniciar sesión nuevamente.');location.href='index.html'}catch(ex){toast(ex.message,'error')}finally{e.target.value=''}});
    if($('#restoreDemoBtn'))$('#restoreDemoBtn').addEventListener('click',()=>{if(confirm('¿Restaurar todos los datos demo? Se perderán los cambios locales.')){try{RentCarStore.resetDemo();location.href='index.html'}catch(e){toast(e.message,'error')}}});
    let searchTimer;$('#globalSearch').addEventListener('input',e=>{clearTimeout(searchTimer);const q=e.target.value.trim();if(q.length<2){hideGlobalSearch();return}searchTimer=setTimeout(()=>runGlobalSearch(q),260)});document.addEventListener('click',e=>{if(!e.target.closest('.global-search'))hideGlobalSearch()});
  }

  async function runGlobalSearch(q){const host=$('#globalResults');try{const rows=await Api.get(`/api/search?q=${encodeURIComponent(q)}`);host.innerHTML=rows.length?rows.map(r=>`<button class="global-result" data-module="${esc(r.module)}"><b>${esc(r.type)}</b><strong>${esc(r.title)}</strong><small>${esc(r.subtitle)}</small></button>`).join(''):'<div class="global-results-empty">Sin coincidencias para esta búsqueda.</div>';host.classList.remove('hidden');host.onclick=e=>{const b=e.target.closest('[data-module]');if(!b)return;location.hash=b.dataset.module;hideGlobalSearch()}}catch{hideGlobalSearch()}}
  function hideGlobalSearch(){const host=$('#globalResults');if(host){host.classList.add('hidden');host.innerHTML=''}}

  function route(){const key=(location.hash||'#dashboard').slice(1);const mod=mods[key]&&has(mods[key].permission)?key:'dashboard';state.current=mod;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.module===mod));loadModule(mod)}
  async function loadModule(key,refresh=false){
    const mod=mods[key];state.current=key;state.query='';hideGlobalSearch();$('#sectionLabel').textContent=mod.section;$('#pageTitle').textContent=mod.title;content.innerHTML='<div class="loading">Cargando información…</div>';
    try{if(mod.special==='dashboard')return renderDashboard(await Api.get('/api/dashboard'));if(mod.special==='reports')return renderReports();if(mod.special==='users')return renderUsers(await Api.get('/api/users'));if(mod.special==='roles')return renderRoles(await Api.get('/api/roles'));if(mod.special==='documents')return renderDocuments(await Api.get('/api/attachments?page=1&pageSize=200'));await renderCrud(mod)}catch(ex){content.innerHTML=`<div class="empty"><strong>No se pudo cargar ${esc(mod.title)}</strong>${esc(ex.message)}</div>`;toast(ex.message,'error')}
  }

  async function renderDashboard(data){
    const k=data.kpis||{},max=Math.max(1,...(data.monthlyRevenue||[]).map(x=>Number(x.amount)));
    const profileNames={SuperAdmin:'Panel de administración',Administrator:'Panel administrativo',OperationsManager:'Panel de operaciones',RentalAgent:'Panel de agente de alquiler',Cashier:'Panel de caja y cobros',FleetManager:'Panel de gestión de flota',Mechanic:'Panel de taller y mantenimiento',HumanResources:'Panel de Recursos Humanos',Auditor:'Panel de auditoría',Management:'Panel gerencial'};
    const cards=[];
    if(k.totalVehicles!==null)cards.push(kpi('Flota activa',k.totalVehicles,'car','vehículos registrados'));
    if(k.available!==null)cards.push(kpi('Disponibles',k.available,'check','listos para alquilar'));
    if(k.rented!==null)cards.push(kpi('Alquilados',k.rented,'file',`${k.utilization||0}% utilización`));
    if(k.revenueMonth!==null)cards.push(kpi('Ingresos del mes',money(k.revenueMonth),'wallet','pagos aprobados'));
    if(k.activeContracts!==null)cards.push(kpi('Contratos activos',k.activeContracts,'clipboard','en circulación'));
    if(k.reservationsToday!==null)cards.push(kpi('Reservas de hoy',k.reservationsToday,'calendar','recogidas previstas'));
    if(k.maintenance!==null)cards.push(kpi('En mantenimiento',k.maintenance,'wrench','vehículos bloqueados'));
    if(k.openDamages!==null)cards.push(kpi('Daños abiertos',k.openDamages,'alert','pendientes de cierre'));
    if(k.pendingMaintenance!==null)cards.push(kpi('Mant. pendientes',k.pendingMaintenance,'clock','programados/en curso'));
    if(k.openCashRegisters!==null)cards.push(kpi('Cajas abiertas',k.openCashRegisters,'wallet','sesiones activas'));
    if(k.employeesActive!==null)cards.push(kpi('Empleados activos',k.employeesActive,'users','personal habilitado'));
    if(k.attendanceToday!==null)cards.push(kpi('Asistencia hoy',k.attendanceToday,'clock','marcaciones registradas'));
    if(k.pendingVacations!==null)cards.push(kpi('Vacaciones pendientes',k.pendingVacations,'calendar','requieren decisión'));
    const analytics=[];
    if((data.monthlyRevenue||[]).length)analytics.push(`<section class="card"><div class="card-head"><strong>Ingresos últimos meses</strong><span>BOB</span></div><div class="card-body"><div class="bar-chart">${data.monthlyRevenue.map(x=>`<div class="bar-col"><div class="bar" style="height:${Math.max(3,Math.round(Number(x.amount)/max*180))}px" data-value="${esc(money(x.amount))}"></div><div class="bar-label">${esc(x.month)}</div></div>`).join('')}</div></div></section>`);
    if((data.vehicleStatus||[]).length)analytics.push(`<section class="card"><div class="card-head"><strong>Estado de flota</strong><span>${k.totalVehicles||0} unidades</span></div><div class="card-body"><div class="donut-wrap"><div class="donut" style="background:conic-gradient(#2d79ef 0 ${Math.max(0,Math.min(100,Number(k.utilization||0)))}%,#e9eef5 ${Math.max(0,Math.min(100,Number(k.utilization||0)))}% 100%)"><div class="donut-center"><strong>${k.utilization||0}%</strong><span>UTILIZACIÓN</span></div></div><div class="legend">${data.vehicleStatus.map(x=>`<div class="legend-row"><span>${esc(human(x.status))}</span><strong>${x.count}</strong></div>`).join('')}</div></div></div></section>`);
    const pending=[];
    if((data.upcomingReservations||[]).length)pending.push(`<section class="card"><div class="card-head"><strong>Reservas próximas</strong><span>7 días</span></div><div class="card-body list-compact">${compactList(data.upcomingReservations,'reservation')}</div></section>`);
    if((data.dueContracts||[]).length)pending.push(`<section class="card"><div class="card-head"><strong>Devoluciones próximas</strong><span>48 horas</span></div><div class="card-body list-compact">${compactList(data.dueContracts,'contract')}</div></section>`);
    content.innerHTML=`<div class="page-head"><div><h2>${esc(profileNames[data.profile]||'Resumen de trabajo')}</h2><p>La información de este panel se limita a los permisos efectivos de tu cuenta.</p></div><div class="page-actions">${has('reports.read')?`<button class="btn" onclick="location.hash='reports'">${Icons.svg('chart')} Ver reportes</button>`:''}${has('reservations.write')?`<button class="btn primary" onclick="location.hash='reservations'">${Icons.svg('plus')} Nueva reserva</button>`:''}</div></div><div class="kpi-grid">${cards.join('')}</div>${analytics.length?`<div class="dashboard-grid">${analytics.join('')}</div>`:''}${pending.length?`<div class="dashboard-grid">${pending.join('')}</div>`:''}`;
  }
  function kpi(label,value,icon,sub){return `<div class="kpi-card"><div class="kpi-top"><span>${esc(label)}</span><div class="kpi-icon">${Icons.svg(icon)}</div></div><div class="kpi-value">${esc(value)}</div><div class="kpi-sub">${esc(sub)}</div></div>`}
  function compactList(rows,type){if(!rows?.length)return '<div class="empty"><strong>Sin pendientes</strong>No existen registros en este rango.</div>';return rows.map(x=>`<div class="list-row"><div><strong>${esc(x.code)}</strong><p>${type==='reservation'?'Recogida':'Devolución'} · ${dateTimeFmt(type==='reservation'?x.pickupAt:x.expectedReturnAt)}</p></div><span class="pill ${type==='contract'?'orange':'green'}">${esc(human(x.status))}</span></div>`).join('')}

  async function renderReports(){
    const financial=has('reports.financial')?await Api.get('/api/reports/summary'):null;
    const hr=has('reports.hr')?await Api.get('/api/reports/hr'):null;
    const cards=[];
    if(financial){cards.push(`<div class="card report-card"><h3>Ingresos del periodo</h3><div class="big">${money(financial.revenue)}</div><p>${financial.payments} pagos aprobados.</p></div>`,`<div class="card report-card"><h3>Contratos iniciados</h3><div class="big">${financial.contracts}</div><p>Promedio: ${money(financial.averageContract)}</p></div>`,`<div class="card report-card"><h3>Costo de mantenimiento</h3><div class="big">${money(financial.maintenanceCost)}</div><p>Costos reales del periodo.</p></div>`)}
    if(hr){cards.push(`<div class="card report-card"><h3>Empleados activos</h3><div class="big">${hr.activeEmployees}</div><p>${hr.attendanceToday} marcaciones hoy.</p></div>`,`<div class="card report-card"><h3>Vacaciones pendientes</h3><div class="big">${hr.vacationsPending}</div><p>${hr.vacationsApproved} solicitudes aprobadas.</p></div>`,`<div class="card report-card"><h3>Contratos por vencer</h3><div class="big">${hr.contractsExpiring60Days}</div><p>Próximos 60 días.</p></div>`)}
    content.innerHTML=`<div class="page-head"><div><h2>Centro de reportes</h2><p>Solo se muestran conjuntos de información habilitados para tu rol.</p></div><div class="page-actions">${has('reports.financial')?`<a class="btn" href="/api/reports/payments.csv">${Icons.svg('download')} Pagos CSV</a>`:''}${has('reports.fleet')?`<button id="fleetReport" class="btn primary">${Icons.svg('car')} Rendimiento de flota</button>`:''}</div></div><div class="report-grid">${cards.join('')||'<div class="card report-card"><h3>Sin reportes asignados</h3><p>Solicita a un administrador permisos de reporte adicionales.</p></div>'}</div>${financial?`<div class="dashboard-grid" style="margin-top:15px"><section class="card"><div class="card-head"><strong>Por método de pago</strong></div><div class="card-body list-compact">${(financial.byPaymentMethod||[]).map(x=>`<div class="list-row"><div><strong>${esc(human(x.method))}</strong><p>${x.count} operaciones</p></div><strong>${money(x.amount)}</strong></div>`).join('')||'<div class="empty">Sin datos</div>'}</div></section><section class="card"><div class="card-head"><strong>Estados de contrato</strong></div><div class="card-body list-compact">${(financial.byContractStatus||[]).map(x=>`<div class="list-row"><strong>${esc(human(x.status))}</strong><span class="pill">${x.count}</span></div>`).join('')||'<div class="empty">Sin datos</div>'}</div></section></div>`:''}`;
    if($('#fleetReport'))$('#fleetReport').addEventListener('click',async()=>{try{const rows=await Api.get('/api/reports/fleet');showDetails('Rendimiento de flota',{registros:rows.length,mejorVehiculo:rows[0]?.vehicle||'—',ingresoMayor:money(rows[0]?.rentalRevenue||0),detalle:rows.map(r=>`${r.code} · ${r.vehicle} · ${money(r.rentalRevenue)}`).join('\n')})}catch(e){toast(e.message,'error')}})
  }

  async function renderCrud(mod){
    await preloadLookups(mod);const data=await Api.get(`${mod.endpoint}?page=1&pageSize=200`);state.rows=data.items||data||[];state.filtered=[...state.rows];
    content.innerHTML=`<div class="page-head"><div><h2>${esc(mod.title)}</h2><p>${moduleDescription(state.current)}</p></div><div class="page-actions">${!mod.readOnly&&mod.allowCreate!==false&&has(mod.write)?`<button id="newBtn" class="btn primary">${Icons.svg('plus')} Nuevo registro</button>`:''}<button id="exportBtn" class="btn">${Icons.svg('download')} CSV</button></div></div><div class="toolbar"><div class="toolbar-search">${Icons.svg('search')}<input id="localSearch" placeholder="Buscar en ${esc(mod.title.toLowerCase())}…"></div><span style="font-size:10px;color:#7b899c">${state.rows.length} registros cargados</span></div><div id="tableHost"></div>`;
    $('#localSearch').addEventListener('input',e=>{state.query=e.target.value.toLowerCase().trim();applyFilter()});$('#exportBtn').addEventListener('click',()=>exportCsv(mod,state.filtered));if($('#newBtn'))$('#newBtn').addEventListener('click',()=>openForm(mod));drawTable(mod)
  }
  function applyFilter(){const q=state.query;if(!q){state.filtered=[...state.rows]}else state.filtered=state.rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q)||Object.values(r).some(v=>String(resolveLookupValue(v)).toLowerCase().includes(q)));const mod=mods[state.current];if(mod&&!mod.special)drawTable(mod)}
  function drawTable(mod){const rows=state.filtered;$('#tableHost').innerHTML=`<div class="table-card"><div class="table-wrap"><table class="data-table"><thead><tr>${mod.columns.map(c=>`<th>${esc(c[1])}</th>`).join('')}<th style="width:145px">Acciones</th></tr></thead><tbody>${rows.map(r=>`<tr>${mod.columns.map(c=>`<td>${formatCell(r[c[0]],c[2],c[0])}</td>`).join('')}<td><div class="actions">${actionButtons(mod,r)}</div></td></tr>`).join('')}</tbody></table></div>${rows.length?`<div class="table-foot"><span>Mostrando ${rows.length} de ${state.rows.length}</span><span>Máximo 200 por vista</span></div>`:'<div class="empty"><strong>No hay resultados</strong>Ajusta la búsqueda o crea un registro.</div>'}</div>`;$('#tableHost').onclick=e=>handleRowAction(e,mod)}
  function actionButtons(mod,r){let s=`<button class="action-btn" data-act="view" data-id="${r.id}" title="Ver">${Icons.svg('eye')}</button>`;if(!mod.readOnly&&has(mod.write)){if(mod.allowEdit!==false)s+=`<button class="action-btn" data-act="edit" data-id="${r.id}" title="Editar">${Icons.svg('edit')}</button>`;for(const a of mod.actions||[])s+=specialActionButton(a,r);if(mod.deletable!==false)s+=`<button class="action-btn danger" data-act="delete" data-id="${r.id}" title="Eliminar/Desactivar">${Icons.svg('trash')}</button>`}return s}
  function specialActionButton(a,r){if(a==='contract'&&['Pending','Confirmed','CheckIn'].includes(r.status))return `<button class="action-btn" data-act="contract" data-id="${r.id}" title="Crear contrato">${Icons.svg('file')}</button>`;if(a==='extend'&&['Active','Extended'].includes(r.status))return `<button class="action-btn" data-act="extend" data-id="${r.id}" title="Extender contrato">${Icons.svg('calendar')}</button>`;if(a==='return'&&['Active','Extended'].includes(r.status))return `<button class="action-btn" data-act="return" data-id="${r.id}" title="Registrar devolución">${Icons.svg('swap')}</button>`;if(a==='close'&&r.status==='Returned')return `<button class="action-btn" data-act="close" data-id="${r.id}" title="Cerrar contrato">${Icons.svg('check')}</button>`;if(a==='maintenanceStatus'&&r.status!=='Completed')return `<button class="action-btn" data-act="maintenanceStatus" data-id="${r.id}" title="Cambiar estado">${Icons.svg('wrench')}</button>`;if(a==='cashClose'&&r.isOpen)return `<button class="action-btn" data-act="cashClose" data-id="${r.id}" title="Cerrar caja">${Icons.svg('wallet')}</button>`;if(a==='vacationDecision'&&r.status==='Pending')return `<button class="action-btn" data-act="vacationDecision" data-id="${r.id}" title="Resolver solicitud">${Icons.svg('check')}</button>`;if(a==='transfer'&&r.status==='Requested')return `<button class="action-btn" data-act="depart" data-id="${r.id}" title="Despachar">${Icons.svg('swap')}</button>`;if(a==='transfer'&&r.status==='InTransit')return `<button class="action-btn" data-act="receive" data-id="${r.id}" title="Recibir">${Icons.svg('check')}</button>`;return ''}
  async function handleRowAction(e,mod){const b=e.target.closest('[data-act]');if(!b)return;const row=state.rows.find(x=>x.id===b.dataset.id);if(!row)return;try{switch(b.dataset.act){case'view':showDetails(`${mod.title} · ${row.code||row.name||''}`,row,mod);break;case'edit':openForm(mod,row);break;case'delete':await removeRow(mod,row);break;case'contract':showContractModal(row);break;case'extend':showExtendModal(row);break;case'return':showReturnModal(row);break;case'close':if(confirm('¿Cerrar este contrato? Se validará que no exista saldo pendiente.')){await Api.post(`/api/contracts/${row.id}/close`,{});toast('Contrato cerrado.');loadModule(state.current)}break;case'maintenanceStatus':showMaintenanceStatus(row);break;case'cashClose':showCashClose(row);break;case'vacationDecision':showVacationDecision(row);break;case'depart':if(confirm('¿Marcar la transferencia como en tránsito?')){await Api.post(`/api/transfers/${row.id}/depart`,{});toast('Vehículo despachado.');loadModule(state.current)}break;case'receive':if(confirm('¿Confirmar recepción del vehículo? Quedará pendiente de inspección.')){await Api.post(`/api/transfers/${row.id}/receive`,{});toast('Transferencia recibida.');loadModule(state.current)}break}}catch(ex){toast(ex.message,'error')}}
  async function removeRow(mod,row){if(!confirm(`¿Confirmas eliminar/desactivar ${row.code||row.name||'este registro'}?`))return;await Api.del(`${mod.endpoint}/${row.id}`);toast('Operación realizada.');await loadModule(state.current)}

  async function preloadLookups(mod){for(const f of mod.fields||[]){if(f.type==='lookup')await loadLookup(f.options)}for(const c of mod.columns||[]){if(String(c[2]||'').startsWith('lookup:'))await loadLookup(c[2].split(':')[1])}}
  async function loadLookup(name){if(state.lookup[name])return state.lookup[name];const m=mods[name];if(!m)return[];try{const d=await Api.get(`${m.endpoint}?page=1&pageSize=200`);state.lookup[name]=d.items||d||[];return state.lookup[name]}catch{return[]}}
  function lookupLabel(name,row){if(!row)return'—';if(name==='vehicles')return `${row.code||''} · ${row.plate||''} · ${row.make||''} ${row.model||''}`.trim();if(name==='customers'||name==='employees')return `${row.code||''} · ${row.firstName||''} ${row.lastName||''}`.trim();if(name==='contracts'||name==='reservations')return row.code||row.id;if(name==='cashRegisters')return row.code||row.id;return `${row.code?row.code+' · ':''}${row.name||row.description||row.key||row.id}`}
  function resolveLookupValue(v){for(const rows of Object.values(state.lookup)){const r=rows.find(x=>x.id===v);if(r)return r.code||r.name||`${r.firstName||''} ${r.lastName||''}`}return v}
  function formatCell(v,type,key){if(type?.startsWith('lookup:')){const n=type.split(':')[1],r=(state.lookup[n]||[]).find(x=>x.id===v);return `<span class="cell-main">${esc(lookupLabel(n,r))}</span>`}if(type==='money')return `<span class="cell-main">${esc(money(v))}</span>`;if(type==='datetime')return dateTimeFmt(v);if(type==='date')return dateFmt(v);if(type==='number')return esc(v??0);if(type==='boolean')return `<span class="pill ${v?'green':'gray'}">${v?'Activo':'Inactivo'}</span>`;if(type==='cash')return `<span class="pill ${v?'green':'gray'}">${v?'Abierta':'Cerrada'}</span>`;if(type==='array')return esc((v||[]).join(', ')||'—');if(type==='status')return `<span class="pill ${statusColor(v)}">${esc(human(v||'—'))}</span>`;return `<span class="cell-main">${esc(v??'—')}</span>`}
  function statusColor(v){v=String(v||'').toLowerCase();if(/available|approved|active|completed|closed|received|repaired|confirmed/.test(v))return'green';if(/pending|scheduled|inspection|extended|assessment|inprogress|intransit/.test(v))return'orange';if(/cancel|reject|critical|breached|outofservice|retired/.test(v))return'red';return'gray'}

  async function openForm(mod,row=null){await preloadLookups(mod);const edit=!!row;const fields=mod.fields||[];openModal(`${edit?'Editar':'Nuevo'} · ${mod.title}`,`<form id="entityForm"><div class="form-grid">${fields.map(f=>fieldHtml(f,row)).join('')}</div></form>`,[{label:'Cancelar',close:true},{label:edit?'Guardar cambios':'Crear registro',primary:true,id:'saveEntity'}]);$('#saveEntity').onclick=async()=>{const form=$('#entityForm');if(!form.reportValidity())return;const body=collectForm(fields,row);try{if(edit)await Api.put(`${mod.endpoint}/${row.id}`,body);else await Api.post(mod.endpoint,body);closeModal();toast(edit?'Cambios guardados.':'Registro creado.');state.lookup={};await loadModule(state.current)}catch(ex){toast(ex.message,'error')}}}
  function fieldHtml(f,row){let val=row?.[f.key];if(f.type==='datetime-local'&&val)val=toLocalInput(val);if(f.type==='checkbox'){const checked=(row?!!val:(f.key==='isActive'));return `<div class="field"><label><input name="${f.key}" type="checkbox" ${checked?'checked':''}> ${esc(f.label)}</label></div>`}let ctl='';const req=f.required?'required':'';if(f.type==='textarea')ctl=`<textarea name="${f.key}" ${req}>${esc(val??'')}</textarea>`;else if(f.type==='select'){const selected=(val===undefined||val===null||val==='')&&!row?(f.options||[])[0]:val;ctl=`<select name="${f.key}" ${req}>${(f.options||[]).map(o=>`<option ${String(selected)===String(o)?'selected':''} value="${esc(o)}">${esc(human(o))}</option>`).join('')}</select>`;}else if(f.type==='lookup'){const rows=state.lookup[f.options]||[];ctl=`<select name="${f.key}" ${req}><option value="">Seleccionar…</option>${rows.map(o=>`<option ${String(val)===String(o.id)?'selected':''} value="${o.id}">${esc(lookupLabel(f.options,o))}</option>`).join('')}</select>`}else ctl=`<input name="${f.key}" type="${f.type||'text'}" value="${esc(val??'')}" ${req} ${f.type==='number'?'step="0.01"':''}>`;return `<div class="field ${f.type==='textarea'?'full':''}"><label>${esc(f.label)}${f.required?' *':''}</label>${ctl}</div>`}
  function collectForm(fields,row){const body=row?{...row}:{};for(const f of fields){const el=document.querySelector(`#entityForm [name="${f.key}"]`);if(!el)continue;if(f.type==='checkbox')body[f.key]=el.checked;else if(f.type==='number')body[f.key]=el.value===''?0:Number(el.value);else if(f.type==='datetime-local')body[f.key]=el.value?new Date(el.value).toISOString():null;else if(['date','time','lookup'].includes(f.type))body[f.key]=el.value||null;else body[f.key]=el.value}delete body.updatedAt;delete body.updatedBy;return body}
  function toLocalInput(v){const d=new Date(v);if(isNaN(d))return'';const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}

  function showDetails(title,row,mod=null){const ignore=new Set(['oldValuesJson','newValuesJson']);const html=Object.entries(row).filter(([k])=>!ignore.has(k)).map(([k,v])=>`<div class="detail"><span>${esc(human(k))}</span><strong>${esc(prettyValue(k,v,mod))}</strong></div>`).join('');openModal(title,`<div class="details-grid">${html}</div>${row.oldValuesJson?`<h4>Valores anteriores</h4><pre>${esc(row.oldValuesJson)}</pre>`:''}${row.newValuesJson?`<h4>Valores nuevos</h4><pre>${esc(row.newValuesJson)}</pre>`:''}`,[{label:'Cerrar',close:true}])}
  function prettyValue(k,v,mod){if(v===null||v===undefined||v==='')return'—';const col=mod?.columns?.find(c=>c[0]===k);if(col?.[2]?.startsWith('lookup:')){const n=col[2].split(':')[1];return lookupLabel(n,(state.lookup[n]||[]).find(x=>x.id===v))}if(typeof v==='boolean')return v?'Sí':'No';if(Array.isArray(v))return v.join(', ');if(typeof v==='object')return JSON.stringify(v,null,2);if(/At$/.test(k))return dateTimeFmt(v).replace(/<[^>]+>/g,'');if(/Date$|On$/.test(k))return dateFmt(v).replace(/<[^>]+>/g,'');return String(v)}
  function openModal(title,body,buttons=[] ,cls=''){const root=$('#modalRoot');root.innerHTML=`<div class="modal-backdrop"><section class="modal ${cls}"><div class="modal-head"><h3>${esc(title)}</h3><button class="modal-close">×</button></div><div class="modal-body">${body}</div><div class="modal-actions">${buttons.map((b,i)=>`<button ${b.id?`id="${b.id}"`:''} data-close="${b.close?'1':'0'}" class="btn ${b.primary?'primary':''} ${b.danger?'danger':''}">${esc(b.label)}</button>`).join('')}</div></section></div>`;root.querySelector('.modal-close').onclick=closeModal;root.querySelectorAll('[data-close="1"]').forEach(b=>b.onclick=closeModal);root.querySelector('.modal-backdrop').addEventListener('click',e=>{if(e.target.classList.contains('modal-backdrop'))closeModal()})}
  function closeModal(){$('#modalRoot').innerHTML=''}

  function showContractModal(res){openModal('Crear contrato desde reserva',`<form id="flowForm"><div class="form-grid"><div class="field"><label>Kilometraje de salida</label><input name="startMileage" type="number" required min="0"></div><div class="field"><label>Combustible inicial %</label><input name="startFuelPercent" type="number" min="0" max="100" value="100" required></div><div class="field"><label>Seguro adicional</label><input name="insuranceAmount" type="number" step="0.01" value="0"></div><div class="field"><label>Extras</label><input name="extrasAmount" type="number" step="0.01" value="0"></div><div class="field"><label>Impuestos</label><input name="taxAmount" type="number" step="0.01" value="0"></div><div class="field full"><label>Observaciones de entrega</label><textarea name="notes"></textarea></div></div></form>`,[{label:'Cancelar',close:true},{label:'Crear y entregar vehículo',primary:true,id:'flowSave'}]);$('#flowSave').onclick=async()=>{const f=$('#flowForm');if(!f.reportValidity())return;const o=Object.fromEntries(new FormData(f));['startMileage','startFuelPercent','insuranceAmount','extrasAmount','taxAmount'].forEach(k=>o[k]=Number(o[k]||0));try{await Api.post(`/api/contracts/from-reservation/${res.id}`,o);closeModal();toast('Contrato creado y vehículo marcado como alquilado.');loadModule(state.current)}catch(e){toast(e.message,'error')}}}
  function showExtendModal(c){openModal(`Extender contrato · ${c.code}`,`<form id="flowForm"><div class="form-grid"><div class="field"><label>Nueva devolución prevista</label><input name="newExpectedReturnAt" type="datetime-local" min="${toLocalInput(c.expectedReturnAt)}" required></div><div class="field"><label>Cargo adicional</label><input name="extensionAmount" type="number" step="0.01" min="0" value="0"></div><div class="field full"><label>Motivo / observaciones</label><textarea name="notes"></textarea></div></div></form>`,[{label:'Cancelar',close:true},{label:'Extender contrato',primary:true,id:'flowSave'}]);$('#flowSave').onclick=async()=>{const f=$('#flowForm');if(!f.reportValidity())return;const o=Object.fromEntries(new FormData(f));o.newExpectedReturnAt=new Date(o.newExpectedReturnAt).toISOString();o.extensionAmount=Number(o.extensionAmount||0);try{await Api.post(`/api/contracts/${c.id}/extend`,o);closeModal();toast('Contrato extendido y nuevo total calculado.');loadModule(state.current)}catch(e){toast(e.message,'error')}}}
  function showReturnModal(c){openModal(`Devolución · ${c.code}`,`<form id="flowForm"><div class="form-grid"><div class="field"><label>Fecha/hora real</label><input name="actualReturnAt" type="datetime-local" value="${toLocalInput(new Date())}" required></div><div class="field"><label>Kilometraje final</label><input name="endMileage" type="number" min="${c.startMileage}" required></div><div class="field"><label>Combustible final %</label><input name="endFuelPercent" type="number" min="0" max="100" value="100" required></div><div class="field"><label>Recargo retraso</label><input name="lateFee" type="number" step="0.01" value="0"></div><div class="field"><label>Recargo combustible</label><input name="fuelFee" type="number" step="0.01" value="0"></div><div class="field"><label>Km excedidos</label><input name="mileageFee" type="number" step="0.01" value="0"></div><div class="field"><label>Daños</label><input name="damageFee" type="number" step="0.01" value="0"></div><div class="field"><label><input name="inspectionApproved" type="checkbox" checked> Inspección aprobada</label></div><div class="field full"><label>Observaciones</label><textarea name="notes"></textarea></div></div></form>`,[{label:'Cancelar',close:true},{label:'Registrar devolución',primary:true,id:'flowSave'}]);$('#flowSave').onclick=async()=>{const f=$('#flowForm');if(!f.reportValidity())return;const fd=new FormData(f),o=Object.fromEntries(fd);o.actualReturnAt=new Date(o.actualReturnAt).toISOString();['endMileage','endFuelPercent','lateFee','fuelFee','mileageFee','damageFee'].forEach(k=>o[k]=Number(o[k]||0));o.inspectionApproved=f.elements.inspectionApproved.checked;try{await Api.post(`/api/contracts/${c.id}/return`,o);closeModal();toast('Devolución registrada e inspección creada.');loadModule(state.current)}catch(e){toast(e.message,'error')}}}
  function showMaintenanceStatus(r){openModal(`Estado mantenimiento · ${r.code}`,`<form id="flowForm"><div class="form-grid"><div class="field"><label>Nuevo estado</label><select name="status" required>${['Scheduled','InProgress','Completed','Cancelled'].map(x=>`<option value="${x}" ${r.status===x?'selected':''}>${human(x)}</option>`).join('')}</select></div><div class="field"><label>Costo real</label><input name="actualCost" type="number" step="0.01" value="${r.actualCost||0}"></div><div class="field"><label>Próxima fecha</label><input name="nextMaintenanceDate" type="date" value="${r.nextMaintenanceDate||''}"></div><div class="field"><label>Próximo kilometraje</label><input name="nextMaintenanceMileage" type="number" value="${r.nextMaintenanceMileage||''}"></div></div></form>`,[{label:'Cancelar',close:true},{label:'Actualizar',primary:true,id:'flowSave'}]);$('#flowSave').onclick=async()=>{const o=Object.fromEntries(new FormData($('#flowForm')));o.actualCost=o.actualCost?Number(o.actualCost):null;o.nextMaintenanceMileage=o.nextMaintenanceMileage?Number(o.nextMaintenanceMileage):null;try{await Api.post(`/api/maintenance/${r.id}/status`,o);closeModal();toast('Estado de mantenimiento actualizado.');loadModule(state.current)}catch(e){toast(e.message,'error')}}}
  function showCashClose(r){openModal(`Cerrar caja · ${r.code}`,`<form id="flowForm"><div class="form-grid"><div class="field"><label>Monto contado al cierre</label><input name="closingAmount" type="number" step="0.01" required></div><div class="field full"><label>Observaciones</label><textarea name="notes"></textarea></div></div></form>`,[{label:'Cancelar',close:true},{label:'Cerrar caja',primary:true,id:'flowSave'}]);$('#flowSave').onclick=async()=>{const o=Object.fromEntries(new FormData($('#flowForm')));o.closingAmount=Number(o.closingAmount);try{await Api.post(`/api/cash-registers/${r.id}/close`,o);closeModal();toast('Caja cerrada y conciliada.');loadModule(state.current)}catch(e){toast(e.message,'error')}}}
  function showVacationDecision(r){openModal(`Resolver vacaciones · ${r.code}`,`<p style="font-size:12px;color:#667389">Selecciona una decisión. La acción quedará registrada en auditoría.</p>`,[{label:'Cancelar',close:true},{label:'Rechazar',danger:true,id:'rejectVac'},{label:'Aprobar',primary:true,id:'approveVac'}],'small');for(const [id,approve] of [['rejectVac',false],['approveVac',true]])$('#'+id).onclick=async()=>{try{await Api.post(`/api/vacations/${r.id}/decision`,{approve});closeModal();toast(approve?'Vacaciones aprobadas.':'Solicitud rechazada.');loadModule(state.current)}catch(e){toast(e.message,'error')}}}

  function canWriteDocumentType(type){const map={Customer:'customers.write',Vehicle:'vehicles.write',RentalContract:'contracts.write',Employee:'hr.write',Damage:'damages.write',Maintenance:'maintenance.write'};return has('attachments.write')&&!!map[type]&&has(map[type])}
  async function renderDocuments(data){
    state.rows=data.items||[];
    content.innerHTML=`<div class="page-head"><div><h2>Documentos y adjuntos</h2><p>Archivos vinculados a clientes, vehículos, contratos, empleados, daños y mantenimientos. Los archivos se almacenan localmente en el navegador y se incluyen en el respaldo JSON.</p></div><div class="page-actions">${has('attachments.write')?`<button id="uploadDoc" class="btn primary">${Icons.svg('plus')} Subir archivo</button>`:''}</div></div><div class="table-card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Archivo</th><th>Categoría</th><th>Entidad</th><th>ID relacionado</th><th>Tamaño</th><th>Fecha</th><th>Acciones</th></tr></thead><tbody>${state.rows.map(r=>`<tr><td class="cell-main">${esc(r.originalFileName)}</td><td>${esc(r.category)}</td><td>${esc(r.relatedEntityType)}</td><td>${esc(r.relatedEntityId)}</td><td>${esc((r.sizeBytes/1024).toFixed(1))} KB</td><td>${dateTimeFmt(r.createdAt)}</td><td><div class="actions"><a class="action-btn" href="/api/attachments/${r.id}/download" title="Descargar">${Icons.svg('download')}</a>${canWriteDocumentType(r.relatedEntityType)?`<button class="action-btn danger" data-doc-delete="${r.id}" title="Eliminar">${Icons.svg('trash')}</button>`:''}</div></td></tr>`).join('')}</tbody></table></div>${state.rows.length?'':'<div class="empty"><strong>Sin documentos</strong>Sube el primer archivo relacionado.</div>'}</div>`;
    if($('#uploadDoc'))$('#uploadDoc').onclick=openDocumentUpload;
    content.querySelectorAll('[data-doc-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('¿Eliminar este archivo y su registro?'))return;try{await Api.del(`/api/attachments/${b.dataset.docDelete}`);toast('Documento eliminado.');loadModule('documents')}catch(e){toast(e.message,'error')}})
  }
  async function openDocumentUpload(){
    const types=[['Customer','customers','customers.write'],['Vehicle','vehicles','vehicles.write'],['RentalContract','contracts','contracts.write'],['Employee','employees','hr.write'],['Damage','damages','damages.write'],['Maintenance','maintenance','maintenance.write']].filter(x=>has(x[2]));
    if(!types.length){toast('No tienes permisos de edición sobre entidades que admitan documentos.','error');return;}
    await Promise.all(types.map(x=>loadLookup(x[1])));
    openModal('Subir documento',`<form id="docForm"><div class="form-grid"><div class="field"><label>Tipo de entidad *</label><select id="docType" name="relatedEntityType" required>${types.map(x=>`<option value="${x[0]}" data-lookup="${x[1]}">${human(x[0])}</option>`).join('')}</select></div><div class="field"><label>Registro relacionado *</label><select id="docEntity" name="relatedEntityId" required></select></div><div class="field"><label>Categoría</label><select name="category"><option>General</option><option>Identidad</option><option>Licencia</option><option>Contrato</option><option>Seguro</option><option>Inspección</option><option>Daño</option><option>Mantenimiento</option><option>Factura</option></select></div><div class="field"><label>Archivo *</label><input name="file" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.docx,.xlsx" required></div><div class="field full"><label>Notas</label><textarea name="notes"></textarea></div></div></form>`,[{label:'Cancelar',close:true},{label:'Subir archivo',primary:true,id:'docSave'}]);
    const typeEl=$('#docType'),entityEl=$('#docEntity');const refill=()=>{const opt=typeEl.selectedOptions[0],name=opt.dataset.lookup,rows=state.lookup[name]||[];entityEl.innerHTML=rows.map(r=>`<option value="${r.id}">${esc(lookupLabel(name,r))}</option>`).join('')};typeEl.onchange=refill;refill();
    $('#docSave').onclick=async()=>{const f=$('#docForm');if(!f.reportValidity())return;const fd=new FormData(f);try{await Api.request('/api/attachments',{method:'POST',body:fd});closeModal();toast('Documento almacenado.');loadModule('documents')}catch(e){toast(e.message,'error')}}
  }

  async function renderUsers(data){state.rows=data.items||[];content.innerHTML=`<div class="page-head"><div><h2>Usuarios del sistema</h2><p>Cuentas, roles, bloqueo e identidad de acceso. Las contraseñas nunca se almacenan en texto plano.</p></div><div class="page-actions">${has('users.write')?`<button id="newUser" class="btn primary">${Icons.svg('plus')} Nuevo usuario</button>`:''}</div></div><div id="tableHost"></div>`;state.filtered=[...state.rows];drawSpecialTable(mods.users);if($('#newUser'))$('#newUser').onclick=()=>openUserForm();}
  function drawSpecialTable(mod){$('#tableHost').innerHTML=`<div class="table-card"><div class="table-wrap"><table class="data-table"><thead><tr>${mod.columns.map(c=>`<th>${c[1]}</th>`).join('')}<th>Acciones</th></tr></thead><tbody>${state.filtered.map(r=>`<tr>${mod.columns.map(c=>`<td>${formatCell(r[c[0]],c[2],c[0])}</td>`).join('')}<td><div class="actions"><button class="action-btn" data-u="view" data-id="${r.id}">${Icons.svg('eye')}</button>${has(mod.write)?`<button class="action-btn" data-u="edit" data-id="${r.id}">${Icons.svg('edit')}</button><button class="action-btn" data-u="reset" data-id="${r.id}">${Icons.svg('key')}</button>`:''}</div></td></tr>`).join('')}</tbody></table></div></div>`;$('#tableHost').onclick=e=>{const b=e.target.closest('[data-u]');if(!b)return;const r=state.rows.find(x=>x.id===b.dataset.id);if(b.dataset.u==='view')showDetails('Usuario',r,mod);if(b.dataset.u==='edit')openUserForm(r);if(b.dataset.u==='reset')resetUserPassword(r)}}
  async function openUserForm(row=null){const rd=await Api.get('/api/roles');const roles=rd.items||[];openModal(row?'Editar usuario':'Nuevo usuario',`<form id="userForm"><div class="form-grid">${!row?`<div class="field"><label>Correo *</label><input name="email" type="email" required></div><div class="field"><label>Contraseña inicial *</label><input name="password" type="password" minlength="12" required></div>`:''}<div class="field ${row?'full':''}"><label>Nombre completo *</label><input name="fullName" value="${esc(row?.fullName||'')}" required></div>${row?`<div class="field"><label><input name="isActive" type="checkbox" ${row.isActive?'checked':''}> Usuario activo</label></div>`:''}<div class="field full"><label>Roles</label><div class="permission-grid">${roles.map(x=>`<label class="permission-item"><input type="checkbox" name="role" value="${esc(x.name)}" ${(row?.roles||[]).includes(x.name)?'checked':''}> ${esc(human(x.name))}</label>`).join('')}</div></div></div></form>`,[{label:'Cancelar',close:true},{label:'Guardar',primary:true,id:'saveUser'}]);$('#saveUser').onclick=async()=>{const f=$('#userForm');if(!f.reportValidity())return;const fd=new FormData(f),o={fullName:fd.get('fullName'),roles:fd.getAll('role')};if(row){o.isActive=f.elements.isActive.checked;o.employeeId=row.employeeId||null;await Api.put(`/api/users/${row.id}`,o)}else{o.email=fd.get('email');o.password=fd.get('password');await Api.post('/api/users',o)}closeModal();toast('Usuario guardado.');loadModule('users')}}
  function resetUserPassword(r){openModal(`Restablecer contraseña · ${r.email}`,`<form id="resetForm"><div class="field"><label>Nueva contraseña</label><input name="password" type="password" minlength="12" required><small>Mínimo 12 caracteres, mayúscula, minúscula, número y símbolo.</small></div></form>`,[{label:'Cancelar',close:true},{label:'Restablecer',primary:true,id:'doReset'}],'small');$('#doReset').onclick=async()=>{const f=$('#resetForm');if(!f.reportValidity())return;try{await Api.post(`/api/users/${r.id}/reset-password`,{newPassword:f.elements.password.value});closeModal();toast('Contraseña restablecida.')}catch(e){toast(e.message,'error')}}}

  function renderRoles(data){state.rows=data.items||[];const catalog=data.permissionCatalog||[];content.innerHTML=`<div class="page-head"><div><h2>Roles y permisos</h2><p>Modelo RBAC local. Cada cuenta recibe solamente los permisos asignados a sus roles.</p></div></div><div class="table-card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Rol</th><th>Permisos asignados</th><th>Acciones</th></tr></thead><tbody>${state.rows.map(r=>`<tr><td class="cell-main">${esc(human(r.name))}</td><td>${r.permissions.length} permisos</td><td><button class="action-btn" data-role="${r.id}" title="Gestionar permisos">${Icons.svg('key')}</button></td></tr>`).join('')}</tbody></table></div></div>`;content.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{const r=state.rows.find(x=>x.id===b.dataset.role);if(has('roles.write'))openRolePermissions(r,catalog);else showDetails('Permisos del rol',r)})}
  function openRolePermissions(role,catalog){openModal(`Permisos · ${human(role.name)}`,`<div class="permission-grid">${catalog.map(p=>`<label class="permission-item"><input type="checkbox" name="perm" value="${p}" ${role.permissions.includes(p)?'checked':''} ${role.name==='SuperAdmin'?'disabled':''}> ${esc(p)}</label>`).join('')}</div>`,[{label:'Cancelar',close:true},{label:'Guardar permisos',primary:true,id:'savePerm'}]);$('#savePerm').disabled=role.name==='SuperAdmin';$('#savePerm').onclick=async()=>{const permissions=[...document.querySelectorAll('[name="perm"]:checked')].map(x=>x.value);try{await Api.put(`/api/roles/${role.id}/permissions`,{permissions});closeModal();toast('Permisos actualizados. Los usuarios deben renovar sesión para reflejar cambios.');loadModule('roles')}catch(e){toast(e.message,'error')}}}

  async function loadNotifications(){try{const rows=await Api.get('/api/notifications');const unread=rows.filter(x=>!x.isRead);$('#notificationCount').textContent=unread.length;$('#notifUnread').textContent=`${unread.length} sin leer`;$('#notificationList').innerHTML=rows.slice(0,15).map(n=>`<div class="notification-row ${n.isRead?'read':''}" data-notif="${n.id}"><i class="notification-dot"></i><div><strong>${esc(n.title)}</strong><p>${esc(n.message)}</p><small>${dateTimeFmt(n.createdAt)} · ${esc(n.module)}</small></div></div>`).join('')||'<div class="empty">Sin notificaciones</div>';$('#notificationList').onclick=async e=>{const r=e.target.closest('[data-notif]');if(r){await Api.post(`/api/notifications/${r.dataset.notif}/read`,{});await loadNotifications()}}}catch{}}
  function showChangePassword(){openModal('Cambiar contraseña',`<form id="pwdForm"><div class="field"><label>Contraseña actual</label><input type="password" name="current" required></div><div class="field" style="margin-top:12px"><label>Nueva contraseña</label><input type="password" name="next" minlength="12" required><small>Mínimo 12 caracteres y política compleja.</small></div></form>`,[{label:'Cancelar',close:true},{label:'Cambiar',primary:true,id:'changePwd'}],'small');$('#changePwd').onclick=async()=>{const f=$('#pwdForm');if(!f.reportValidity())return;try{await Api.post('/api/auth/change-password',{currentPassword:f.elements.current.value,newPassword:f.elements.next.value});closeModal();toast('Contraseña actualizada.')}catch(e){toast(e.message,'error')}}}

  function exportCsv(mod,rows){const cols=mod.columns;const csv=[cols.map(c=>csvEsc(c[1])).join(','),...rows.map(r=>cols.map(c=>csvEsc(prettyValue(c[0],r[c[0]],mod))).join(','))].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download=`rentcar-${state.current}-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  const csvEsc=v=>`"${String(v??'').replace(/"/g,'""')}"`;
  function moduleDescription(k){return {reservations:'Planificación de disponibilidad, recogidas y reservas sin superposición.',contracts:'Entrega, alquiler activo, devolución, recargos y cierre financiero.',customers:'Ficha de cliente, licencia, contacto y restricciones.',vehicles:'Inventario de flota, documentación, tarifas y estado operativo.',vehicleCategories:'Segmentos comerciales y tarifas base.',inspections:'Control de salida, retorno y liberación posterior a mantenimiento.',damages:'Expedientes de daños, responsable, seguro y costos.',maintenance:'Mantenimiento preventivo/correctivo y bloqueo de disponibilidad.',transfers:'Movimientos de vehículos entre sucursales con trazabilidad.',payments:'Cobros, depósitos, recargos, devoluciones y referencias.',invoices:'Comprobantes internos asociados a cliente y contrato; la integración fiscal externa se registra por referencia.',documents:'Repositorio seguro de documentos relacionados con entidades del sistema.',cashRegisters:'Apertura, conciliación y cierre diario de caja.',branches:'Puntos de operación y disponibilidad territorial.',employees:'Expediente laboral y asignación organizacional.',attendance:'Entradas, salidas, atrasos y horas extraordinarias.',vacations:'Solicitudes y flujo de aprobación de vacaciones.',employeeContracts:'Contratos laborales, salarios y vigencias.',evaluations:'Desempeño periódico del personal.',departments:'Estructura organizacional.',positions:'Cargos y responsabilidades.',settings:'Parámetros configurables del sistema.',audit:'Registro inmutable de cambios sobre entidades de negocio.'}[k]||'Gestión operativa de RentCar Professional.'}

  boot();
})();
