(()=>{
  'use strict';
  const DB_KEY='rentcar_professional_html_db_v3', SESSION_KEY='rentcar_professional_session_v3', REMEMBER_KEY='rentcar_professional_remember_v3';
  function nativeStore(kind){try{const s=window[kind+'Storage'];const k='__rc_storage_test__';s.setItem(k,'1');s.removeItem(k);return s}catch{return null}}
  const nativeLocal=nativeStore('local'),nativeSession=nativeStore('session');
  function fallbackState(){try{return JSON.parse(window.name||'{}')}catch{return{}}}
  function fbGet(kind,key){const f=fallbackState();return f[kind]?.[key]??null}
  function fbSet(kind,key,val){const f=fallbackState();f[kind]=f[kind]||{};f[kind][key]=String(val);window.name=JSON.stringify(f)}
  function fbRemove(kind,key){const f=fallbackState();if(f[kind])delete f[kind][key];window.name=JSON.stringify(f)}
  const LS={getItem:k=>nativeLocal?nativeLocal.getItem(k):fbGet('local',k),setItem:(k,v)=>nativeLocal?nativeLocal.setItem(k,v):fbSet('local',k,v),removeItem:k=>nativeLocal?nativeLocal.removeItem(k):fbRemove('local',k)};
  const SS={getItem:k=>nativeSession?nativeSession.getItem(k):fbGet('session',k),setItem:(k,v)=>nativeSession?nativeSession.setItem(k,v):fbSet('session',k,v),removeItem:k=>nativeSession?nativeSession.removeItem(k):fbRemove('session',k)};
  const endpointMap={
    '/api/vehicles':'vehicles','/api/vehicle-categories':'vehicleCategories','/api/customers':'customers','/api/reservations':'reservations','/api/contracts':'contracts','/api/inspections':'inspections','/api/damages':'damages','/api/maintenance':'maintenance','/api/transfers':'transfers','/api/payments':'payments','/api/invoices':'invoices','/api/cash-registers':'cashRegisters','/api/branches':'branches','/api/employees':'employees','/api/attendance':'attendance','/api/vacations':'vacations','/api/employee-contracts':'employeeContracts','/api/evaluations':'evaluations','/api/departments':'departments','/api/positions':'positions','/api/attachments':'attachments','/api/settings':'settings','/api/audit':'audit'
  };
  const endpointPerm={
    vehicles:['vehicles.read','vehicles.write'],'vehicleCategories':['vehicles.read','vehicles.write'],customers:['customers.read','customers.write'],reservations:['reservations.read','reservations.write'],contracts:['contracts.read','contracts.write'],inspections:['inspections.read','inspections.write'],damages:['damages.read','damages.write'],maintenance:['maintenance.read','maintenance.write'],transfers:['transfers.read','transfers.write'],payments:['payments.read','payments.write'],invoices:['payments.read','payments.write'],cashRegisters:['cash.read','cash.write'],branches:['branches.read','branches.write'],employees:['hr.read','hr.write'],attendance:['hr.read','hr.write'],vacations:['hr.read','hr.write'],employeeContracts:['hr.read','hr.write'],evaluations:['hr.read','hr.write'],departments:['hr.read','hr.write'],positions:['hr.read','hr.write'],attachments:['attachments.read','attachments.write'],settings:['settings.read','settings.write'],audit:['audit.read',null]
  };
  const deep=v=>JSON.parse(JSON.stringify(v));
  function init(){ if(!LS.getItem(DB_KEY)) save(deep(window.RENTCAR_SEED)); }
  function db(){init(); try{return JSON.parse(LS.getItem(DB_KEY))}catch{const d=deep(window.RENTCAR_SEED);save(d);return d}}
  function save(d){LS.setItem(DB_KEY,JSON.stringify(d))}
  function now(){return new Date().toISOString()}
  function uuid(){return (crypto&&crypto.randomUUID)?crypto.randomUUID():'id-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)}
  function parse(url){return new URL(url,'https://rentcar.local')}
  function currentUser(d=db()){
    const id=SS.getItem(SESSION_KEY)||LS.getItem(REMEMBER_KEY); if(!id)return null;
    const u=d.users.find(x=>x.id===id); if(!u||!u.isActive)return null; return u;
  }
  function permsFor(u,d=db()){ if(!u)return[]; return [...new Set((u.roles||[]).flatMap(r=>d.roles.find(x=>x.name===r)?.permissions||[]))] }
  function me(){const d=db(),u=currentUser(d);if(!u)throw new Error('Sesión no iniciada.');return {id:u.id,email:u.email,fullName:u.fullName,roles:u.roles,isActive:u.isActive,permissions:permsFor(u,d),employeeId:u.employeeId,lastLoginAt:u.lastLoginAt}}
  function requireAuth(){return me()}
  function requirePerm(p){if(!p)return;const u=me();if(!u.permissions.includes(p))throw new Error('No tienes permisos para realizar esta acción.')}
  function audit(d,module,action,entityName,entityId,details=''){const u=currentUser(d);d.audit.unshift({id:uuid(),occurredAt:now(),userName:u?.fullName||'Sistema local',module,action,entityName,entityId:String(entityId||''),ipAddress:'Local browser',details})}
  function sha256(ascii){function rr(v,a){return(v>>>a)|(v<<(32-a))}var p=Math.pow,m=p(2,32),l='length',i,j,res='',w=[],bl=ascii[l]*8,h=sha256.h=sha256.h||[],k=sha256.k=sha256.k||[],pc=k[l],comp={};for(var c=2;pc<64;c++){if(!comp[c]){for(i=0;i<313;i+=c)comp[i]=c;h[pc]=(p(c,.5)*m)|0;k[pc++]=(p(c,1/3)*m)|0}}ascii+='\x80';while(ascii[l]%64-56)ascii+='\x00';for(i=0;i<ascii[l];i++){j=ascii.charCodeAt(i);if(j>>8)return'';w[i>>2]|=j<<((3-i)%4)*8}w[w[l]]=bl/m|0;w[w[l]]=bl;for(j=0;j<w[l];){var a=w.slice(j,j+=16),old=h;h=h.slice(0,8);for(i=0;i<64;i++){var w15=a[i-15],w2=a[i-2],A=h[0],e=h[4],t1=h[7]+(rr(e,6)^rr(e,11)^rr(e,25))+((e&h[5])^((~e)&h[6]))+k[i]+(a[i]=(i<16)?a[i]:(a[i-16]+(rr(w15,7)^rr(w15,18)^(w15>>>3))+a[i-7]+(rr(w2,17)^rr(w2,19)^(w2>>>10)))|0),t2=(rr(A,2)^rr(A,13)^rr(A,22))+((A&h[1])^(A&h[2])^(h[1]&h[2]));h=[(t1+t2)|0].concat(h);h[4]=(h[4]+t1)|0}for(i=0;i<8;i++)h[i]=(h[i]+old[i])|0}for(i=0;i<8;i++)for(j=3;j+1;j--){var b=(h[i]>>(j*8))&255;res+=(b<16?'0':'')+b.toString(16)}return res}
  function passwordOk(p){return typeof p==='string'&&p.length>=12&&/[A-Z]/.test(p)&&/[a-z]/.test(p)&&/\d/.test(p)&&/[^A-Za-z0-9]/.test(p)}
  function prefixFor(col){return {vehicles:'VEH',vehicleCategories:'CAT',customers:'CLI',reservations:'RES',contracts:'CTR',inspections:'INS',damages:'DMG',maintenance:'MNT',transfers:'TRF',payments:'PAY',invoices:'FAC',cashRegisters:'CAJ',branches:'SUC',employees:'EMP',attendance:'ASI',vacations:'VAC',employeeContracts:'LAB',evaluations:'EVA',departments:'DEP',positions:'CAR'}[col]||'REG'}
  function nextCode(d,col){const p=prefixFor(col), n=(d[col]||[]).length+1; if(['reservations','contracts','inspections','damages','maintenance','transfers','payments','invoices','cashRegisters','vacations','employeeContracts','evaluations'].includes(col))return `${p}-${new Date().getFullYear()}-${String(n).padStart(6,'0')}`; if(col==='customers')return `${p}-${String(n).padStart(6,'0')}`; return `${p}-${String(n).padStart(3,'0')}`}
  const num=v=>Number(v||0), days=(a,b)=>Math.max(1,Math.ceil((new Date(b)-new Date(a))/86400000));
  function overlaps(a1,a2,b1,b2){return new Date(a1)<new Date(b2)&&new Date(a2)>new Date(b1)}
  function validateReservation(d,o,ignoreId=null){
    if(!o.customerId||!o.vehicleId||!o.pickupAt||!o.returnAt)throw new Error('Cliente, vehículo y fechas son obligatorios.');
    if(new Date(o.returnAt)<=new Date(o.pickupAt))throw new Error('La devolución debe ser posterior a la recogida.');
    const c=d.customers.find(x=>x.id===o.customerId);if(!c||!c.isActive)throw new Error('Cliente no disponible.');if(c.isBlacklisted)throw new Error('El cliente está restringido para alquileres.');if(c.licenseExpiresOn&&new Date(c.licenseExpiresOn)<new Date(o.returnAt))throw new Error('La licencia del cliente vence antes de finalizar la reserva.');
    const v=d.vehicles.find(x=>x.id===o.vehicleId);if(!v)throw new Error('Vehículo no encontrado.');if(['Maintenance','OutOfService','Retired'].includes(v.status))throw new Error('El vehículo no está operativo.');if(v.insuranceExpiresOn&&new Date(v.insuranceExpiresOn)<new Date(o.returnAt))throw new Error('El seguro del vehículo no cubre todo el periodo.');if(v.technicalInspectionExpiresOn&&new Date(v.technicalInspectionExpiresOn)<new Date(o.returnAt))throw new Error('La inspección técnica vence durante el periodo.');
    const bad=d.reservations.some(r=>r.id!==ignoreId&&r.vehicleId===o.vehicleId&&!['Cancelled','NoShow','Completed','Converted'].includes(r.status)&&overlaps(o.pickupAt,o.returnAt,r.pickupAt,r.returnAt));if(bad)throw new Error('El vehículo ya tiene una reserva superpuesta en esas fechas.');
    const cBad=d.contracts.some(r=>r.vehicleId===o.vehicleId&&['Active','Extended'].includes(r.status)&&overlaps(o.pickupAt,o.returnAt,r.startsAt,r.expectedReturnAt));if(cBad)throw new Error('El vehículo tiene un contrato activo que se superpone con esas fechas.');
  }
  function recalcReservation(d,o){const v=d.vehicles.find(x=>x.id===o.vehicleId);o.baseRate=num(v?.dailyRate);o.estimatedTotal=Math.max(0,o.baseRate*days(o.pickupAt,o.returnAt)-num(o.discount)+num(o.extrasTotal)+num(o.taxTotal));if(o.depositAmount===undefined||o.depositAmount===null||o.depositAmount==='')o.depositAmount=num(v?.depositAmount);return o}
  function computeEval(o){const vals=['punctualityScore','performanceScore','productivityScore','teamworkScore','customerServiceScore'].map(k=>num(o[k])).filter(x=>x>0);o.overallScore=vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length*10)/10:0;}
  function genericGet(d,col){return {items:deep(d[col]||[]),total:(d[col]||[]).length}}
  function genericCreate(d,col,body){const o={id:uuid(),...deep(body)};if(['vehicleCategories','branches','departments','positions'].includes(col)&&o.isActive===undefined)o.isActive=true;if(col==='employees'&&o.isActive===undefined)o.isActive=true;if(col==='customers'&&o.isActive===undefined)o.isActive=true;if(!o.code&&['vehicles','vehicleCategories','customers','reservations','inspections','damages','maintenance','transfers','payments','invoices','cashRegisters','branches','employees','vacations','employeeContracts','evaluations','departments','positions'].includes(col))o.code=nextCode(d,col);if(col==='reservations'){validateReservation(d,o);recalcReservation(d,o);o.status=o.status||'Confirmed';const v=d.vehicles.find(x=>x.id===o.vehicleId);if(v&&['Available','Reserved'].includes(v.status))v.status='Reserved'}if(col==='maintenance'){o.status=o.status||'Scheduled';if(['Scheduled','InProgress'].includes(o.status)){const v=d.vehicles.find(x=>x.id===o.vehicleId);if(v)v.status='Maintenance'}}if(col==='transfers'){o.status='Requested';o.requestedAt=o.requestedAt||now()}if(col==='cashRegisters'){o.openedAt=now();o.expectedAmount=num(o.openingAmount);o.closingAmount=null;o.difference=0;o.isOpen=true}if(col==='evaluations')computeEval(o);if(col==='payments'){o.paidAt=o.paidAt||now();o.status=o.status||'Approved';o.currency=o.currency||'BOB'}if(col==='inspections'){o.inspectedAt=o.inspectedAt||now();if(o.status==='Approved'){const v=d.vehicles.find(x=>x.id===o.vehicleId);if(v&&['Maintenance','Inspection'].includes(v.status))v.status='Available'}}d[col].unshift(o);audit(d,col,'CREATE',col,o.id,JSON.stringify(o));save(d);return deep(o)}
  function genericUpdate(d,col,id,body){const i=d[col].findIndex(x=>x.id===id);if(i<0)throw new Error('Registro no encontrado.');const before=deep(d[col][i]),o={...d[col][i],...deep(body),id};if(col==='reservations'){validateReservation(d,o,id);recalcReservation(d,o)}if(col==='evaluations')computeEval(o);d[col][i]=o;audit(d,col,'UPDATE',col,id,`Antes: ${JSON.stringify(before)} | Después: ${JSON.stringify(o)}`);save(d);return deep(o)}
  function dependent(d,col,id){const refs={customers:[['reservations','customerId'],['contracts','customerId'],['payments','customerId']],vehicles:[['reservations','vehicleId'],['contracts','vehicleId'],['maintenance','vehicleId'],['damages','vehicleId']],branches:[['vehicles','branchId'],['reservations','pickupBranchId'],['employees','branchId']],employees:[['reservations','assignedEmployeeId'],['attendance','employeeId'],['vacations','employeeId']],vehicleCategories:[['vehicles','categoryId']],departments:[['employees','departmentId'],['positions','departmentId']],positions:[['employees','positionId']]};return (refs[col]||[]).some(([c,k])=>(d[c]||[]).some(x=>x[k]===id))}
  function genericDelete(d,col,id){const i=d[col].findIndex(x=>x.id===id);if(i<0)throw new Error('Registro no encontrado.');if(dependent(d,col,id)){if('isActive'in d[col][i]){d[col][i].isActive=false;audit(d,col,'DEACTIVATE',col,id,'Registro con dependencias desactivado.');save(d);return null}throw new Error('No se puede eliminar: el registro está relacionado con otras operaciones.');}const old=d[col].splice(i,1)[0];audit(d,col,'DELETE',col,id,JSON.stringify(old));save(d);return null}
  function dashboard(d){const u=me(),p=u.permissions,can=x=>p.includes(x), month=new Date().toISOString().slice(0,7);const revenue=d.payments.filter(x=>x.status==='Approved'&&String(x.paidAt).slice(0,7)===month).reduce((s,x)=>s+num(x.amount),0);const total=d.vehicles.filter(v=>v.status!=='Retired').length,rented=d.vehicles.filter(v=>v.status==='Rented').length;const k={totalVehicles:can('vehicles.read')?total:null,available:can('vehicles.read')?d.vehicles.filter(v=>v.status==='Available').length:null,rented:can('vehicles.read')?rented:null,utilization:total?Math.round(rented/total*100):0,revenueMonth:can('payments.read')?revenue:null,activeContracts:can('contracts.read')?d.contracts.filter(x=>['Active','Extended'].includes(x.status)).length:null,reservationsToday:can('reservations.read')?d.reservations.filter(x=>String(x.pickupAt).slice(0,10)===new Date().toISOString().slice(0,10)).length:null,maintenance:can('vehicles.read')?d.vehicles.filter(v=>v.status==='Maintenance').length:null,openDamages:can('damages.read')?d.damages.filter(x=>x.status!=='Closed').length:null,pendingMaintenance:can('maintenance.read')?d.maintenance.filter(x=>['Scheduled','InProgress'].includes(x.status)).length:null,openCashRegisters:can('cash.read')?d.cashRegisters.filter(x=>x.isOpen).length:null,employeesActive:can('hr.read')?d.employees.filter(x=>x.isActive).length:null,attendanceToday:can('hr.read')?d.attendance.filter(x=>x.date===new Date().toISOString().slice(0,10)).length:null,pendingVacations:can('hr.read')?d.vacations.filter(x=>x.status==='Pending').length:null};
    const months=[];for(let i=5;i>=0;i--){const dt=new Date();dt.setMonth(dt.getMonth()-i);const key=dt.toISOString().slice(0,7);months.push({month:dt.toLocaleString('es-BO',{month:'short'}),amount:d.payments.filter(x=>x.status==='Approved'&&String(x.paidAt).slice(0,7)===key).reduce((s,x)=>s+num(x.amount),0)})}if(months.every(x=>x.amount===0)){months[3].amount=3850;months[4].amount=5420;months[5].amount=revenue||7210}
    const statuses=[...new Set(d.vehicles.map(v=>v.status))].map(status=>({status,count:d.vehicles.filter(v=>v.status===status).length}));const soon=new Date(Date.now()+7*86400000), due48=new Date(Date.now()+48*3600000);
    return {profile:u.roles[0]||'User',kpis:k,monthlyRevenue:can('payments.read')?months:[],vehicleStatus:can('vehicles.read')?statuses:[],upcomingReservations:can('reservations.read')?d.reservations.filter(r=>new Date(r.pickupAt)>=new Date()&&new Date(r.pickupAt)<=soon&&!['Cancelled','Completed','Converted'].includes(r.status)).slice(0,5):[],dueContracts:can('contracts.read')?d.contracts.filter(c=>['Active','Extended'].includes(c.status)&&new Date(c.expectedReturnAt)<=due48).slice(0,5):[]}
  }
  function reportSummary(d){const pays=d.payments.filter(x=>x.status==='Approved'), revenue=pays.reduce((s,x)=>s+num(x.amount),0), cs=d.contracts;const byPaymentMethod=[...new Set(pays.map(x=>x.method))].map(method=>({method,count:pays.filter(x=>x.method===method).length,amount:pays.filter(x=>x.method===method).reduce((s,x)=>s+num(x.amount),0)}));const byContractStatus=[...new Set(cs.map(x=>x.status))].map(status=>({status,count:cs.filter(x=>x.status===status).length}));return {revenue,payments:pays.length,contracts:cs.length,averageContract:cs.length?cs.reduce((s,x)=>s+num(x.totalAmount),0)/cs.length:0,maintenanceCost:d.maintenance.reduce((s,x)=>s+num(x.actualCost),0),byPaymentMethod,byContractStatus}}
  function reportHr(d){const lim=new Date(Date.now()+60*86400000);return {activeEmployees:d.employees.filter(x=>x.isActive).length,attendanceToday:d.attendance.filter(x=>x.date===new Date().toISOString().slice(0,10)).length,vacationsPending:d.vacations.filter(x=>x.status==='Pending').length,vacationsApproved:d.vacations.filter(x=>x.status==='Approved').length,contractsExpiring60Days:d.employeeContracts.filter(x=>x.endDate&&new Date(x.endDate)<=lim&&new Date(x.endDate)>=new Date()).length}}
  function reportFleet(d){return d.vehicles.map(v=>{const cs=d.contracts.filter(c=>c.vehicleId===v.id),ids=new Set(cs.map(c=>c.id));const rev=d.payments.filter(p=>ids.has(p.rentalContractId)&&p.status==='Approved').reduce((s,p)=>s+num(p.amount),0);return {code:v.code,vehicle:`${v.make} ${v.model} · ${v.plate}`,rentals:cs.length,rentalRevenue:rev,mileage:v.mileage,status:v.status}}).sort((a,b)=>b.rentalRevenue-a.rentalRevenue)}
  function search(d,q){q=q.toLowerCase();const out=[];const add=(module,type,title,subtitle)=>{if((title+' '+subtitle).toLowerCase().includes(q))out.push({module,type,title,subtitle})};d.vehicles.forEach(x=>add('vehicles','Vehículo',`${x.code} · ${x.plate}`,`${x.make} ${x.model}`));d.customers.forEach(x=>add('customers','Cliente',`${x.code} · ${x.firstName} ${x.lastName}`,x.documentNumber));d.reservations.forEach(x=>add('reservations','Reserva',x.code,`${x.status} · ${x.pickupAt}`));d.contracts.forEach(x=>add('contracts','Contrato',x.code,`${x.status} · ${x.expectedReturnAt}`));d.employees.forEach(x=>add('employees','Empleado',`${x.code} · ${x.firstName} ${x.lastName}`,x.email));return out.slice(0,20)}
  function downloadBlob(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),800)}
  function csvPayments(){const d=db(),rows=d.payments;const esc=v=>'"'+String(v??'').replace(/"/g,'""')+'"';return ['Código,Fecha,Cliente,Concepto,Método,Monto,Moneda,Estado',...rows.map(r=>[r.code,r.paidAt,r.customerId,r.concept,r.method,r.amount,r.currency,r.status].map(esc).join(','))].join('\r\n')}
  async function fileToDataUrl(file){return await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
  async function request(url,options={}){
    init();const method=(options.method||'GET').toUpperCase(),u=parse(url),path=u.pathname,d=db();
    if(path==='/api/auth/login'&&method==='POST'){const b=typeof options.body==='string'?JSON.parse(options.body):options.body||{}, email=String(b.email||'').toLowerCase().trim(), usr=d.users.find(x=>x.email.toLowerCase()===email);if(!usr)throw new Error('Correo o contraseña incorrectos.');if(!usr.isActive)throw new Error('La cuenta está desactivada.');if(usr.lockedUntil&&new Date(usr.lockedUntil)>new Date())throw new Error('Cuenta bloqueada temporalmente por intentos fallidos.');if(sha256(String(b.password||''))!==usr.passwordHash){usr.accessFailedCount=num(usr.accessFailedCount)+1;if(usr.accessFailedCount>=5){usr.lockedUntil=new Date(Date.now()+15*60000).toISOString();usr.accessFailedCount=0}save(d);throw new Error('Correo o contraseña incorrectos.');}usr.accessFailedCount=0;usr.lockedUntil=null;usr.lastLoginAt=now();if(b.rememberMe){LS.setItem(REMEMBER_KEY,usr.id);SS.removeItem(SESSION_KEY)}else{SS.setItem(SESSION_KEY,usr.id);LS.removeItem(REMEMBER_KEY)}audit(d,'Autenticación','LOGIN','User',usr.id,'Inicio de sesión local');save(d);return {ok:true}}
    if(path==='/api/auth/me'&&method==='GET')return me();
    if(path==='/api/auth/logout'&&method==='POST'){const cu=currentUser(d);if(cu)audit(d,'Autenticación','LOGOUT','User',cu.id,'Cierre de sesión');save(d);SS.removeItem(SESSION_KEY);LS.removeItem(REMEMBER_KEY);return {ok:true}}
    if(path==='/api/auth/change-password'&&method==='POST'){const b=JSON.parse(options.body||'{}'),cu=currentUser(d);if(!cu)throw new Error('Sesión no iniciada.');if(sha256(String(b.currentPassword||''))!==cu.passwordHash)throw new Error('La contraseña actual es incorrecta.');if(!passwordOk(b.newPassword))throw new Error('La nueva contraseña debe tener 12+ caracteres, mayúscula, minúscula, número y símbolo.');cu.passwordHash=sha256(b.newPassword);audit(d,'Usuarios','PASSWORD_CHANGE','User',cu.id,'Cambio de contraseña');save(d);return {ok:true}}
    requireAuth();
    if(path==='/api/dashboard'){requirePerm('dashboard.view');return dashboard(d)}
    if(path==='/api/notifications'&&method==='GET')return deep(d.notifications);
    let m=path.match(/^\/api\/notifications\/([^/]+)\/read$/);if(m&&method==='POST'){const n=d.notifications.find(x=>x.id===m[1]);if(n)n.isRead=true;save(d);return {ok:true}}
    if(path==='/api/search'){return search(d,u.searchParams.get('q')||'')}
    if(path==='/api/reports/summary'){requirePerm('reports.financial');return reportSummary(d)}
    if(path==='/api/reports/hr'){requirePerm('reports.hr');return reportHr(d)}
    if(path==='/api/reports/fleet'){requirePerm('reports.fleet');return reportFleet(d)}
    if(path==='/api/users'&&method==='GET'){requirePerm('users.read');return {items:d.users.map(({passwordHash,...x})=>deep(x)),total:d.users.length}}
    if(path==='/api/users'&&method==='POST'){requirePerm('users.write');const b=JSON.parse(options.body||'{}');if(!b.email||d.users.some(x=>x.email.toLowerCase()===String(b.email).toLowerCase()))throw new Error('El correo ya existe o es inválido.');if(!passwordOk(b.password))throw new Error('Contraseña: mínimo 12 caracteres, mayúscula, minúscula, número y símbolo.');const x={id:uuid(),email:b.email.toLowerCase(),passwordHash:sha256(b.password),fullName:b.fullName,roles:b.roles||[],employeeId:b.employeeId||null,isActive:true,lastLoginAt:null,accessFailedCount:0,lockedUntil:null,createdAt:now()};d.users.unshift(x);audit(d,'Usuarios','CREATE','User',x.id,x.email);save(d);const {passwordHash,...safe}=x;return safe}
    m=path.match(/^\/api\/users\/([^/]+)$/);if(m&&method==='PUT'){requirePerm('users.write');const x=d.users.find(z=>z.id===m[1]);if(!x)throw new Error('Usuario no encontrado.');Object.assign(x,JSON.parse(options.body||'{}'));audit(d,'Usuarios','UPDATE','User',x.id,x.email);save(d);const {passwordHash,...safe}=x;return safe}
    m=path.match(/^\/api\/users\/([^/]+)\/reset-password$/);if(m&&method==='POST'){requirePerm('users.write');const x=d.users.find(z=>z.id===m[1]),b=JSON.parse(options.body||'{}');if(!x)throw new Error('Usuario no encontrado.');if(!passwordOk(b.newPassword))throw new Error('La contraseña no cumple la política.');x.passwordHash=sha256(b.newPassword);x.accessFailedCount=0;x.lockedUntil=null;audit(d,'Usuarios','PASSWORD_RESET','User',x.id,x.email);save(d);return {ok:true}}
    if(path==='/api/roles'&&method==='GET'){requirePerm('roles.read');return {items:deep(d.roles),permissionCatalog:deep(d.permissionCatalog)}}
    m=path.match(/^\/api\/roles\/([^/]+)\/permissions$/);if(m&&method==='PUT'){requirePerm('roles.write');const r=d.roles.find(x=>x.id===m[1]),b=JSON.parse(options.body||'{}');if(!r)throw new Error('Rol no encontrado.');if(r.name==='SuperAdmin')throw new Error('No se puede limitar SuperAdmin en esta edición.');r.permissions=(b.permissions||[]).filter(x=>d.permissionCatalog.includes(x));audit(d,'Roles','UPDATE_PERMISSIONS','Role',r.id,r.name);save(d);return deep(r)}
    m=path.match(/^\/api\/contracts\/from-reservation\/([^/]+)$/);if(m&&method==='POST'){requirePerm('contracts.write');const r=d.reservations.find(x=>x.id===m[1]);if(!r||!['Pending','Confirmed','CheckIn'].includes(r.status))throw new Error('La reserva no puede convertirse en contrato.');validateReservation(d,r,r.id);const b=JSON.parse(options.body||'{}'),v=d.vehicles.find(x=>x.id===r.vehicleId),c={id:uuid(),code:nextCode(d,'contracts'),reservationId:r.id,customerId:r.customerId,vehicleId:r.vehicleId,pickupBranchId:r.pickupBranchId,returnBranchId:r.returnBranchId,startsAt:r.pickupAt,expectedReturnAt:r.returnAt,actualReturnAt:null,startMileage:num(b.startMileage),endMileage:null,startFuelPercent:num(b.startFuelPercent),endFuelPercent:null,baseAmount:num(r.estimatedTotal)-num(r.extrasTotal)-num(r.taxTotal)+num(r.discount),insuranceAmount:num(b.insuranceAmount),extrasAmount:num(b.extrasAmount),depositAmount:num(r.depositAmount),taxAmount:num(b.taxAmount),lateFee:0,fuelFee:0,mileageFee:0,damageFee:0,totalAmount:num(r.estimatedTotal)+num(b.insuranceAmount)+num(b.extrasAmount)+num(b.taxAmount),status:'Active',assignedEmployeeId:r.assignedEmployeeId,notes:b.notes||''};d.contracts.unshift(c);r.status='Converted';v.status='Rented';d.inspections.unshift({id:uuid(),code:nextCode(d,'inspections'),vehicleId:v.id,rentalContractId:c.id,type:'Checkout',status:'Approved',inspectedAt:now(),mileage:c.startMileage,fuelPercent:c.startFuelPercent,lightsOk:true,tiresOk:true,windshieldOk:true,bodyOk:true,interiorOk:true,toolsOk:true,spareTireOk:true,documentsOk:true,inspectedByEmployeeId:r.assignedEmployeeId,notes:'Generada al entregar el vehículo'});audit(d,'Contratos','CREATE_FROM_RESERVATION','RentalContract',c.id,c.code);save(d);return deep(c)}
    m=path.match(/^\/api\/contracts\/([^/]+)\/extend$/);if(m&&method==='POST'){requirePerm('contracts.write');const c=d.contracts.find(x=>x.id===m[1]),b=JSON.parse(options.body||'{}');if(!c||!['Active','Extended'].includes(c.status))throw new Error('Contrato no extensible.');if(new Date(b.newExpectedReturnAt)<=new Date(c.expectedReturnAt))throw new Error('La nueva fecha debe ser posterior.');const conflict=d.reservations.some(r=>r.vehicleId===c.vehicleId&&!['Cancelled','Completed','Converted','NoShow'].includes(r.status)&&overlaps(c.expectedReturnAt,b.newExpectedReturnAt,r.pickupAt,r.returnAt));if(conflict)throw new Error('Existe una reserva futura que impide extender el contrato.');c.expectedReturnAt=b.newExpectedReturnAt;c.totalAmount+=num(b.extensionAmount);c.status='Extended';c.notes=(c.notes||'')+'\nExtensión: '+(b.notes||'');audit(d,'Contratos','EXTEND','RentalContract',c.id,JSON.stringify(b));save(d);return deep(c)}
    m=path.match(/^\/api\/contracts\/([^/]+)\/return$/);if(m&&method==='POST'){requirePerm('contracts.write');const c=d.contracts.find(x=>x.id===m[1]),b=JSON.parse(options.body||'{}');if(!c||!['Active','Extended'].includes(c.status))throw new Error('Contrato no activo.');if(num(b.endMileage)<num(c.startMileage))throw new Error('El kilometraje final no puede ser menor al inicial.');Object.assign(c,{actualReturnAt:b.actualReturnAt,endMileage:num(b.endMileage),endFuelPercent:num(b.endFuelPercent),lateFee:num(b.lateFee),fuelFee:num(b.fuelFee),mileageFee:num(b.mileageFee),damageFee:num(b.damageFee),status:'Returned'});c.totalAmount=num(c.totalAmount)+c.lateFee+c.fuelFee+c.mileageFee+c.damageFee;const v=d.vehicles.find(x=>x.id===c.vehicleId);if(v){v.mileage=c.endMileage;v.status=b.inspectionApproved?'Available':'OutOfService'}d.inspections.unshift({id:uuid(),code:nextCode(d,'inspections'),vehicleId:c.vehicleId,rentalContractId:c.id,type:'Return',status:b.inspectionApproved?'Approved':'Rejected',inspectedAt:b.actualReturnAt,mileage:c.endMileage,fuelPercent:c.endFuelPercent,lightsOk:true,tiresOk:true,windshieldOk:true,bodyOk:b.damageFee?false:true,interiorOk:true,toolsOk:true,spareTireOk:true,documentsOk:true,inspectedByEmployeeId:c.assignedEmployeeId,notes:b.notes||''});if(c.damageFee>0)d.damages.unshift({id:uuid(),code:nextCode(d,'damages'),vehicleId:c.vehicleId,rentalContractId:c.id,customerId:c.customerId,reportedAt:b.actualReturnAt,damageType:'Daño en devolución',vehicleArea:'Por inspeccionar',description:b.notes||'Daño registrado durante devolución',severity:'Medium',responsibleParty:'Cliente / por definir',estimatedCost:c.damageFee,actualCost:0,insuranceInvolved:false,status:'Reported'});audit(d,'Contratos','RETURN','RentalContract',c.id,JSON.stringify(b));save(d);return deep(c)}
    m=path.match(/^\/api\/contracts\/([^/]+)\/close$/);if(m&&method==='POST'){requirePerm('contracts.write');const c=d.contracts.find(x=>x.id===m[1]);if(!c||c.status!=='Returned')throw new Error('Solo se puede cerrar un contrato devuelto.');const paid=d.payments.filter(p=>p.rentalContractId===c.id&&p.status==='Approved').reduce((s,p)=>s+num(p.amount),0);if(paid+0.001<num(c.totalAmount))throw new Error(`Existe saldo pendiente de Bs ${(num(c.totalAmount)-paid).toFixed(2)}.`);c.status='Closed';audit(d,'Contratos','CLOSE','RentalContract',c.id,c.code);save(d);return deep(c)}
    m=path.match(/^\/api\/maintenance\/([^/]+)\/status$/);if(m&&method==='POST'){requirePerm('maintenance.write');const x=d.maintenance.find(z=>z.id===m[1]),b=JSON.parse(options.body||'{}');if(!x)throw new Error('Mantenimiento no encontrado.');Object.assign(x,b);const v=d.vehicles.find(z=>z.id===x.vehicleId);if(v){if(['Scheduled','InProgress'].includes(x.status))v.status='Maintenance';if(x.status==='Cancelled')v.status='Available';if(x.status==='Completed'){v.status='Inspection';d.inspections.unshift({id:uuid(),code:nextCode(d,'inspections'),vehicleId:v.id,rentalContractId:null,type:'MaintenanceRelease',status:'Pending',inspectedAt:now(),mileage:v.mileage,fuelPercent:75,lightsOk:true,tiresOk:true,windshieldOk:true,bodyOk:true,interiorOk:true,toolsOk:true,spareTireOk:true,documentsOk:true,inspectedByEmployeeId:x.responsibleEmployeeId,notes:'Pendiente de liberación posterior a mantenimiento'})}}audit(d,'Mantenimiento','STATUS','Maintenance',x.id,JSON.stringify(b));save(d);return deep(x)}
    m=path.match(/^\/api\/cash-registers\/([^/]+)\/close$/);if(m&&method==='POST'){requirePerm('cash.write');const x=d.cashRegisters.find(z=>z.id===m[1]),b=JSON.parse(options.body||'{}');if(!x||!x.isOpen)throw new Error('La caja ya está cerrada o no existe.');const movement=d.payments.filter(p=>p.cashRegisterId===x.id&&p.status==='Approved').reduce((s,p)=>s+num(p.amount),0);x.expectedAmount=num(x.openingAmount)+movement;x.closingAmount=num(b.closingAmount);x.difference=x.closingAmount-x.expectedAmount;x.closedAt=now();x.isOpen=false;x.notes=(x.notes||'')+'\n'+(b.notes||'');audit(d,'Caja','CLOSE','CashRegister',x.id,JSON.stringify(b));save(d);return deep(x)}
    m=path.match(/^\/api\/vacations\/([^/]+)\/decision$/);if(m&&method==='POST'){requirePerm('hr.write');const x=d.vacations.find(z=>z.id===m[1]),b=JSON.parse(options.body||'{}'),u=currentUser(d);if(!x)throw new Error('Solicitud no encontrada.');x.status=b.approve?'Approved':'Rejected';x.decidedAt=now();x.decidedByEmployeeId=u?.employeeId||null;audit(d,'Vacaciones','DECISION','Vacation',x.id,x.status);save(d);return deep(x)}
    m=path.match(/^\/api\/transfers\/([^/]+)\/(depart|receive)$/);if(m&&method==='POST'){requirePerm('transfers.write');const x=d.transfers.find(z=>z.id===m[1]),action=m[2];if(!x)throw new Error('Transferencia no encontrada.');const v=d.vehicles.find(z=>z.id===x.vehicleId);if(action==='depart'){if(x.status!=='Requested')throw new Error('La transferencia no está solicitada.');x.status='InTransit';x.departedAt=now();if(v)v.status='OutOfService'}else{if(x.status!=='InTransit')throw new Error('La transferencia no está en tránsito.');x.status='Received';x.receivedAt=now();if(v){v.branchId=x.toBranchId;v.status='Inspection'}d.inspections.unshift({id:uuid(),code:nextCode(d,'inspections'),vehicleId:x.vehicleId,rentalContractId:null,type:'MaintenanceRelease',status:'Pending',inspectedAt:now(),mileage:v?.mileage||x.startMileage,fuelPercent:75,lightsOk:true,tiresOk:true,windshieldOk:true,bodyOk:true,interiorOk:true,toolsOk:true,spareTireOk:true,documentsOk:true,inspectedByEmployeeId:x.responsibleEmployeeId,notes:'Inspección posterior a transferencia'})}audit(d,'Transferencias',action.toUpperCase(),'Transfer',x.id,x.code);save(d);return deep(x)}
    if(path==='/api/attachments'&&method==='POST'){requirePerm('attachments.write');const fd=options.body;if(!(fd instanceof FormData))throw new Error('Formulario de archivo inválido.');const file=fd.get('file');if(!file||!file.name)throw new Error('Selecciona un archivo.');if(file.size>750*1024)throw new Error('En la edición HTML local los adjuntos se limitan a 750 KB por el límite del navegador.');const x={id:uuid(),originalFileName:file.name,category:String(fd.get('category')||'General'),relatedEntityType:String(fd.get('relatedEntityType')||''),relatedEntityId:String(fd.get('relatedEntityId')||''),sizeBytes:file.size,createdAt:now(),notes:String(fd.get('notes')||''),dataUrl:await fileToDataUrl(file)};d.attachments.unshift(x);audit(d,'Documentos','UPLOAD','Attachment',x.id,x.originalFileName);save(d);return deep(x)}
    let basePath=path, id=null;for(const ep of Object.keys(endpointMap).sort((a,b)=>b.length-a.length)){if(path===ep||path.startsWith(ep+'/')){basePath=ep;id=path===ep?null:path.slice(ep.length+1).split('/')[0];break}}
    const col=endpointMap[basePath];if(col){const [rp,wp]=endpointPerm[col]||[];if(method==='GET'){requirePerm(rp);return genericGet(d,col)}if(method==='POST'){requirePerm(wp);const body=options.body instanceof FormData?Object.fromEntries(options.body):JSON.parse(options.body||'{}');return genericCreate(d,col,body)}if(method==='PUT'){requirePerm(wp);return genericUpdate(d,col,id,JSON.parse(options.body||'{}'))}if(method==='DELETE'){requirePerm(wp);return genericDelete(d,col,id)}}
    throw new Error('Ruta local no implementada: '+path+' ['+method+']');
  }
  window.Api={csrfToken:'local',async csrf(){return'local'},async request(url,options={}){return request(url,options)},get(url){return request(url)},post(url,data){return request(url,{method:'POST',body:JSON.stringify(data)})},put(url,data){return request(url,{method:'PUT',body:JSON.stringify(data)})},del(url){return request(url,{method:'DELETE'})}};
  window.RentCarStore={
    getDatabase(){return deep(db())},
    downloadBackup(){requirePerm('settings.read');downloadBlob(`rentcar-backup-${new Date().toISOString().slice(0,10)}.json`,new Blob([JSON.stringify(db(),null,2)],{type:'application/json'}))},
    async importBackupFile(file){requirePerm('settings.write');const txt=await file.text(),obj=JSON.parse(txt);if(!obj||!Array.isArray(obj.users)||!Array.isArray(obj.vehicles))throw new Error('El archivo no parece ser un respaldo válido de RentCar.');save(obj);SS.removeItem(SESSION_KEY);LS.removeItem(REMEMBER_KEY);return true},
    resetDemo(){requirePerm('settings.write');save(deep(window.RENTCAR_SEED));SS.removeItem(SESSION_KEY);LS.removeItem(REMEMBER_KEY)},
    downloadAttachment(id){const x=db().attachments.find(a=>a.id===id);if(!x)throw new Error('Documento no encontrado.');if(x.dataUrl){const a=document.createElement('a');a.href=x.dataUrl;a.download=x.originalFileName;a.click()}else downloadBlob(x.originalFileName,new Blob([`RentCar Professional\nDocumento local: ${x.originalFileName}\nCategoría: ${x.category}`],{type:'text/plain'}))},
    downloadPaymentsCsv(){requirePerm('reports.financial');downloadBlob(`rentcar-pagos-${new Date().toISOString().slice(0,10)}.csv`,new Blob(['\ufeff'+csvPayments()],{type:'text/csv;charset=utf-8'}))}
  };
  document.addEventListener('click',e=>{const a=e.target.closest?.('a[href^="/api/"]');if(!a)return;const h=a.getAttribute('href');if(h==='/api/reports/payments.csv'){e.preventDefault();try{window.RentCarStore.downloadPaymentsCsv()}catch(err){alert(err.message)}return}const m=h.match(/^\/api\/attachments\/([^/]+)\/download$/);if(m){e.preventDefault();try{window.RentCarStore.downloadAttachment(m[1])}catch(err){alert(err.message)}}},true);
  init();
})();
