window.ModuleCatalog={
  groups:[
    {label:'GENERAL',items:['dashboard','reports']},
    {label:'OPERACIONES',items:['reservations','contracts','customers']},
    {label:'FLOTA',items:['vehicles','vehicleCategories','inspections','damages','maintenance','transfers']},
    {label:'FINANZAS',items:['payments','invoices','cashRegisters']},
    {label:'ORGANIZACIÓN',items:['branches','documents']},
    {label:'RECURSOS HUMANOS',items:['employees','attendance','vacations','employeeContracts','evaluations','departments','positions']},
    {label:'ADMINISTRACIÓN',items:['users','roles','settings','audit']}
  ],
  modules:{
    dashboard:{title:'Dashboard',section:'VISIÓN GENERAL',icon:'grid',permission:'dashboard.view',special:'dashboard'},
    reports:{title:'Reportes',section:'ANÁLISIS',icon:'chart',permission:'reports.read',special:'reports'},
    reservations:{title:'Reservas',deletable:false,section:'OPERACIONES',icon:'calendar',endpoint:'/api/reservations',permission:'reservations.read',write:'reservations.write',code:'code',columns:[['code','Reserva'],['customerId','Cliente','lookup:customers'],['vehicleId','Vehículo','lookup:vehicles'],['pickupAt','Recogida','datetime'],['returnAt','Devolución','datetime'],['estimatedTotal','Total estimado','money'],['status','Estado','status']],fields:[
      F('customerId','Cliente','lookup','customers',true),F('vehicleId','Vehículo','lookup','vehicles',true),F('pickupBranchId','Sucursal de recogida','lookup','branches',true),F('returnBranchId','Sucursal de devolución','lookup','branches',true),F('pickupAt','Fecha/hora de recogida','datetime-local',null,true),F('returnAt','Fecha/hora de devolución','datetime-local',null,true),F('discount','Descuento','number'),F('extrasTotal','Extras','number'),F('taxTotal','Impuestos','number'),F('depositAmount','Depósito','number'),F('status','Estado','select',['Pending','Confirmed','CheckIn','Converted','Cancelled','NoShow','Completed'],true),F('assignedEmployeeId','Empleado responsable','lookup','employees'),F('notes','Observaciones','textarea')],actions:['contract']},
    contracts:{title:'Contratos de alquiler',allowCreate:false,allowEdit:false,deletable:false,section:'OPERACIONES',icon:'file',endpoint:'/api/contracts',permission:'contracts.read',write:'contracts.write',columns:[['code','Contrato'],['customerId','Cliente','lookup:customers'],['vehicleId','Vehículo','lookup:vehicles'],['startsAt','Inicio','datetime'],['expectedReturnAt','Devolución prevista','datetime'],['totalAmount','Total','money'],['status','Estado','status']],fields:[F('customerId','Cliente','lookup','customers',true),F('vehicleId','Vehículo','lookup','vehicles',true),F('pickupBranchId','Sucursal recogida','lookup','branches',true),F('returnBranchId','Sucursal devolución','lookup','branches',true),F('startsAt','Inicio','datetime-local',null,true),F('expectedReturnAt','Devolución prevista','datetime-local',null,true),F('startMileage','Km inicial','number'),F('startFuelPercent','Combustible inicial %','number'),F('baseAmount','Base','number'),F('insuranceAmount','Seguro','number'),F('extrasAmount','Extras','number'),F('depositAmount','Depósito','number'),F('taxAmount','Impuesto','number'),F('totalAmount','Total','number'),F('status','Estado','select',['Preparing','Active','Extended','Returned','Closed','Cancelled','Breached']),F('assignedEmployeeId','Empleado','lookup','employees'),F('notes','Observaciones','textarea')],actions:['extend','return','close']},
    customers:{title:'Clientes',section:'OPERACIONES',icon:'users',endpoint:'/api/customers',permission:'customers.read',write:'customers.write',columns:[['code','Código'],['firstName','Nombre'],['lastName','Apellido'],['documentNumber','Documento'],['licenseNumber','Licencia'],['phone','Teléfono'],['email','Correo'],['isActive','Estado','boolean']],fields:[F('customerType','Tipo','select',['Individual','Empresa']),F('firstName','Nombres','text',null,true),F('lastName','Apellidos','text',null,true),F('documentNumber','Documento','text',null,true),F('taxId','NIT','text'),F('birthDate','Fecha de nacimiento','date'),F('licenseNumber','N.º licencia','text',null,true),F('licenseCategory','Categoría licencia','text'),F('licenseExpiresOn','Vencimiento licencia','date'),F('phone','Teléfono','text'),F('email','Correo','email'),F('address','Dirección','text'),F('city','Ciudad','text'),F('country','País','text'),F('emergencyContact','Contacto de emergencia','text'),F('emergencyPhone','Teléfono emergencia','text'),F('isBlacklisted','Lista de restricción','checkbox'),F('isActive','Activo','checkbox'),F('notes','Observaciones','textarea')]},
    vehicles:{title:'Vehículos',section:'FLOTA',icon:'car',endpoint:'/api/vehicles',permission:'vehicles.read',write:'vehicles.write',columns:[['code','Código'],['plate','Placa'],['make','Marca'],['model','Modelo'],['year','Año'],['mileage','Kilometraje','number'],['branchId','Sucursal','lookup:branches'],['dailyRate','Tarifa/día','money'],['status','Estado','status']],fields:[F('vin','VIN / Chasis','text',null,true),F('plate','Placa','text',null,true),F('make','Marca','text',null,true),F('model','Modelo','text',null,true),F('trim','Versión','text'),F('year','Año','number',null,true),F('color','Color','text'),F('categoryId','Categoría','lookup','vehicleCategories',true),F('transmission','Transmisión','select',['Automática','Manual']),F('fuelType','Combustible','select',['Gasolina','Diésel','Híbrido','Eléctrico']),F('doors','Puertas','number'),F('seats','Pasajeros','number'),F('mileage','Kilometraje','number'),F('acquisitionMileage','Km de adquisición','number'),F('branchId','Sucursal','lookup','branches',true),F('dailyRate','Tarifa diaria','number',null,true),F('weeklyRate','Tarifa semanal','number'),F('depositAmount','Depósito','number'),F('status','Estado','select',['Available','Reserved','Rented','Inspection','Maintenance','OutOfService','Retired']),F('insuranceProvider','Aseguradora','text'),F('insurancePolicy','Póliza','text'),F('insuranceExpiresOn','Vencimiento seguro','date'),F('technicalInspectionExpiresOn','Vencimiento inspección','date'),F('acquisitionDate','Fecha adquisición','date'),F('acquisitionCost','Costo adquisición','number'),F('owner','Propietario','text'),F('notes','Observaciones','textarea')]},
    vehicleCategories:{title:'Categorías de vehículo',section:'FLOTA',icon:'file',endpoint:'/api/vehicle-categories',permission:'vehicles.read',write:'vehicles.write',columns:[['code','Código'],['name','Categoría'],['dailyRate','Tarifa diaria','money'],['weeklyRate','Tarifa semanal','money'],['depositAmount','Depósito','money'],['isActive','Estado','boolean']],fields:[F('name','Nombre','text',null,true),F('dailyRate','Tarifa diaria','number',null,true),F('weeklyRate','Tarifa semanal','number'),F('depositAmount','Depósito','number'),F('isActive','Activo','checkbox')]},
    inspections:{title:'Inspecciones',deletable:false,section:'FLOTA',icon:'clipboard',endpoint:'/api/inspections',permission:'inspections.read',write:'inspections.write',columns:[['code','Código'],['vehicleId','Vehículo','lookup:vehicles'],['type','Tipo'],['inspectedAt','Fecha','datetime'],['mileage','Km','number'],['fuelPercent','Combustible %','number'],['status','Estado','status']],fields:[F('vehicleId','Vehículo','lookup','vehicles',true),F('rentalContractId','Contrato','lookup','contracts'),F('type','Tipo','select',['Checkout','Return','MaintenanceRelease']),F('status','Resultado','select',['Pending','Approved','Rejected']),F('inspectedAt','Fecha','datetime-local',null,true),F('mileage','Kilometraje','number'),F('fuelPercent','Combustible %','number'),F('lightsOk','Luces OK','checkbox'),F('tiresOk','Neumáticos OK','checkbox'),F('windshieldOk','Parabrisas OK','checkbox'),F('bodyOk','Carrocería OK','checkbox'),F('interiorOk','Interior OK','checkbox'),F('toolsOk','Herramientas OK','checkbox'),F('spareTireOk','Repuesto OK','checkbox'),F('documentsOk','Documentos OK','checkbox'),F('inspectedByEmployeeId','Inspector','lookup','employees'),F('notes','Observaciones','textarea')]},
    damages:{title:'Daños',deletable:false,section:'FLOTA',icon:'alert',endpoint:'/api/damages',permission:'damages.read',write:'damages.write',columns:[['code','Código'],['vehicleId','Vehículo','lookup:vehicles'],['damageType','Tipo'],['vehicleArea','Zona'],['severity','Severidad','status'],['estimatedCost','Estimado','money'],['actualCost','Real','money'],['status','Estado','status']],fields:[F('vehicleId','Vehículo','lookup','vehicles',true),F('rentalContractId','Contrato','lookup','contracts'),F('customerId','Cliente','lookup','customers'),F('reportedAt','Fecha reporte','datetime-local',null,true),F('damageType','Tipo de daño','text'),F('vehicleArea','Zona del vehículo','text'),F('description','Descripción','textarea',null,true),F('severity','Severidad','select',['Low','Medium','High','Critical']),F('responsibleParty','Responsable','text'),F('estimatedCost','Costo estimado','number'),F('actualCost','Costo real','number'),F('insuranceInvolved','Seguro involucrado','checkbox'),F('status','Estado','select',['Reported','Assessment','Approved','Repairing','Repaired','Closed'])]},
    maintenance:{title:'Mantenimientos',deletable:false,section:'FLOTA',icon:'wrench',endpoint:'/api/maintenance',permission:'maintenance.read',write:'maintenance.write',columns:[['code','Código'],['vehicleId','Vehículo','lookup:vehicles'],['type','Tipo'],['scheduledAt','Programado','datetime'],['workshop','Taller'],['estimatedCost','Estimado','money'],['actualCost','Real','money'],['status','Estado','status']],fields:[F('vehicleId','Vehículo','lookup','vehicles',true),F('type','Tipo','select',['Preventive','Corrective']),F('status','Estado','select',['Scheduled','InProgress','Completed','Cancelled']),F('workshop','Taller','text'),F('scheduledAt','Fecha programada','datetime-local',null,true),F('mileage','Kilometraje','number'),F('workDescription','Trabajo','textarea'),F('estimatedCost','Costo estimado','number'),F('actualCost','Costo real','number'),F('nextMaintenanceDate','Próximo mantenimiento','date'),F('nextMaintenanceMileage','Próximo km','number'),F('responsibleEmployeeId','Responsable','lookup','employees')],actions:['maintenanceStatus']},
    transfers:{title:'Transferencias',deletable:false,section:'FLOTA',icon:'swap',endpoint:'/api/transfers',permission:'transfers.read',write:'transfers.write',columns:[['code','Código'],['vehicleId','Vehículo','lookup:vehicles'],['fromBranchId','Origen','lookup:branches'],['toBranchId','Destino','lookup:branches'],['requestedAt','Solicitada','datetime'],['status','Estado','status']],fields:[F('vehicleId','Vehículo','lookup','vehicles',true),F('fromBranchId','Origen','lookup','branches',true),F('toBranchId','Destino','lookup','branches',true),F('responsibleEmployeeId','Responsable','lookup','employees'),F('startMileage','Km salida','number')],actions:['transfer']},
    payments:{title:'Pagos',deletable:false,section:'FINANZAS',icon:'wallet',endpoint:'/api/payments',permission:'payments.read',write:'payments.write',columns:[['code','Código'],['paidAt','Fecha','datetime'],['customerId','Cliente','lookup:customers'],['concept','Concepto'],['method','Método'],['amount','Monto','money'],['status','Estado','status']],fields:[F('rentalContractId','Contrato','lookup','contracts'),F('customerId','Cliente','lookup','customers',true),F('paidAt','Fecha','datetime-local',null,true),F('concept','Concepto','text',null,true),F('type','Tipo','select',['Reservation','Rental','Deposit','Damage','Extension','Fine','DepositRefund','Other']),F('method','Método','select',['Cash','Card','Transfer','QR']),F('amount','Monto','number',null,true),F('currency','Moneda','select',['BOB','USD']),F('reference','Referencia','text'),F('status','Estado','select',['Pending','Approved','Refunded','Cancelled']),F('cashRegisterId','Caja','lookup','cashRegisters'),F('receivedByEmployeeId','Recibido por','lookup','employees')]},
    invoices:{title:'Comprobantes',deletable:false,section:'FINANZAS',icon:'file',endpoint:'/api/invoices',permission:'payments.read',write:'payments.write',columns:[['code','Comprobante'],['issuedAt','Fecha','datetime'],['customerId','Cliente','lookup:customers'],['rentalContractId','Contrato','lookup:contracts'],['customerName','Razón social'],['taxId','NIT'],['total','Total','money'],['status','Estado','status']],fields:[F('customerId','Cliente','lookup','customers',true),F('rentalContractId','Contrato','lookup','contracts'),F('issuedAt','Emisión','datetime-local',null,true),F('taxId','NIT','text'),F('customerName','Nombre / Razón social','text'),F('subtotal','Subtotal','number'),F('taxAmount','Impuestos','number'),F('discount','Descuento','number'),F('status','Estado','select',['Draft','Issued','Paid','Cancelled']),F('externalFiscalReference','Referencia fiscal externa','text'),F('notes','Observaciones','textarea')]},
    cashRegisters:{title:'Caja',deletable:false,section:'FINANZAS',icon:'wallet',endpoint:'/api/cash-registers',permission:'cash.read',write:'cash.write',columns:[['code','Caja'],['branchId','Sucursal','lookup:branches'],['employeeId','Empleado','lookup:employees'],['openedAt','Apertura','datetime'],['openingAmount','Monto inicial','money'],['expectedAmount','Esperado','money'],['closingAmount','Cierre','money'],['difference','Diferencia','money'],['isOpen','Estado','cash']],fields:[F('branchId','Sucursal','lookup','branches',true),F('employeeId','Empleado','lookup','employees',true),F('openingAmount','Monto inicial','number',null,true),F('notes','Observaciones','textarea')],actions:['cashClose']},
    documents:{title:'Documentos y adjuntos',section:'ORGANIZACIÓN',icon:'file',endpoint:'/api/attachments',permission:'attachments.read',write:'attachments.write',special:'documents'},
    branches:{title:'Sucursales',section:'ORGANIZACIÓN',icon:'building',endpoint:'/api/branches',permission:'branches.read',write:'branches.write',columns:[['code','Código'],['name','Sucursal'],['city','Ciudad'],['address','Dirección'],['phone','Teléfono'],['manager','Responsable'],['isActive','Estado','boolean']],fields:[F('name','Nombre','text',null,true),F('city','Ciudad','text',null,true),F('address','Dirección','text'),F('phone','Teléfono','text'),F('manager','Responsable','text'),F('openingHours','Horario','text'),F('isActive','Activa','checkbox')]},
    employees:{title:'Empleados',section:'RECURSOS HUMANOS',icon:'users',endpoint:'/api/employees',permission:'hr.read',write:'hr.write',columns:[['code','Código'],['firstName','Nombre'],['lastName','Apellido'],['documentNumber','Documento'],['departmentId','Departamento','lookup:departments'],['positionId','Cargo','lookup:positions'],['branchId','Sucursal','lookup:branches'],['isActive','Estado','boolean']],fields:[F('firstName','Nombres','text',null,true),F('lastName','Apellidos','text',null,true),F('documentNumber','Documento','text',null,true),F('birthDate','Nacimiento','date'),F('phone','Teléfono','text'),F('email','Correo','email'),F('address','Dirección','text'),F('departmentId','Departamento','lookup','departments',true),F('positionId','Cargo','lookup','positions',true),F('branchId','Sucursal','lookup','branches',true),F('supervisorId','Supervisor','lookup','employees'),F('hireDate','Fecha ingreso','date',null,true),F('salary','Salario','number'),F('workSchedule','Horario','text'),F('isActive','Activo','checkbox')]},
    attendance:{title:'Asistencia',deletable:false,section:'RECURSOS HUMANOS',icon:'clock',endpoint:'/api/attendance',permission:'hr.read',write:'hr.write',columns:[['employeeId','Empleado','lookup:employees'],['date','Fecha','date'],['checkIn','Entrada'],['checkOut','Salida'],['workedHours','Horas'],['lateMinutes','Atraso min'],['overtimeHours','Horas extra']],fields:[F('employeeId','Empleado','lookup','employees',true),F('date','Fecha','date',null,true),F('checkIn','Entrada','time'),F('checkOut','Salida','time'),F('workedHours','Horas trabajadas','number'),F('lateMinutes','Atraso (min)','number'),F('overtimeHours','Horas extra','number'),F('notes','Observaciones','textarea')]},
    vacations:{title:'Vacaciones',deletable:false,section:'RECURSOS HUMANOS',icon:'calendar',endpoint:'/api/vacations',permission:'hr.read',write:'hr.write',columns:[['code','Solicitud'],['employeeId','Empleado','lookup:employees'],['startDate','Desde','date'],['endDate','Hasta','date'],['status','Estado','status'],['reason','Motivo']],fields:[F('employeeId','Empleado','lookup','employees',true),F('startDate','Desde','date',null,true),F('endDate','Hasta','date',null,true),F('reason','Motivo','textarea')],actions:['vacationDecision']},
    employeeContracts:{title:'Contratos laborales',deletable:false,section:'RECURSOS HUMANOS',icon:'file',endpoint:'/api/employee-contracts',permission:'hr.read',write:'hr.write',columns:[['code','Código'],['employeeId','Empleado','lookup:employees'],['contractType','Tipo'],['startDate','Inicio','date'],['endDate','Fin','date'],['salary','Salario','money'],['status','Estado','status']],fields:[F('employeeId','Empleado','lookup','employees',true),F('contractType','Tipo','select',['Indefinido','Plazo fijo','Temporal','Consultoría']),F('startDate','Inicio','date',null,true),F('endDate','Fin','date'),F('salary','Salario','number'),F('status','Estado','select',['Draft','Active','Suspended','Expired','Terminated']),F('terms','Condiciones','textarea')]},
    evaluations:{title:'Evaluaciones',deletable:false,section:'RECURSOS HUMANOS',icon:'chart',endpoint:'/api/evaluations',permission:'hr.read',write:'hr.write',columns:[['code','Código'],['employeeId','Empleado','lookup:employees'],['period','Periodo'],['overallScore','Promedio','number'],['notes','Observaciones']],fields:[F('employeeId','Empleado','lookup','employees',true),F('evaluatorEmployeeId','Evaluador','lookup','employees'),F('period','Periodo','text',null,true),F('punctualityScore','Puntualidad 1-5','number'),F('performanceScore','Desempeño 1-5','number'),F('productivityScore','Productividad 1-5','number'),F('teamworkScore','Trabajo en equipo 1-5','number'),F('customerServiceScore','Atención al cliente 1-5','number'),F('notes','Observaciones','textarea')]},
    departments:{title:'Departamentos',section:'RECURSOS HUMANOS',icon:'building',endpoint:'/api/departments',permission:'hr.read',write:'hr.write',columns:[['code','Código'],['name','Departamento'],['description','Descripción'],['isActive','Estado','boolean']],fields:[F('name','Nombre','text',null,true),F('description','Descripción','textarea'),F('managerEmployeeId','Responsable','lookup','employees'),F('isActive','Activo','checkbox')]},
    positions:{title:'Cargos',section:'RECURSOS HUMANOS',icon:'file',endpoint:'/api/positions',permission:'hr.read',write:'hr.write',columns:[['code','Código'],['name','Cargo'],['departmentId','Departamento','lookup:departments'],['description','Descripción'],['isActive','Estado','boolean']],fields:[F('name','Nombre','text',null,true),F('departmentId','Departamento','lookup','departments',true),F('description','Descripción','textarea'),F('isActive','Activo','checkbox')]},
    users:{title:'Usuarios',section:'ADMINISTRACIÓN',icon:'shield',endpoint:'/api/users',permission:'users.read',write:'users.write',special:'users',columns:[['email','Correo'],['fullName','Nombre'],['roles','Roles','array'],['isActive','Estado','boolean'],['lastLoginAt','Último acceso','datetime'],['accessFailedCount','Fallos','number']]},
    roles:{title:'Roles y permisos',section:'ADMINISTRACIÓN',icon:'key',endpoint:'/api/roles',permission:'roles.read',write:'roles.write',special:'roles',columns:[['name','Rol'],['permissions','Permisos','array']]},
    settings:{title:'Configuración',section:'ADMINISTRACIÓN',icon:'settings',endpoint:'/api/settings',permission:'settings.read',write:'settings.write',columns:[['category','Categoría'],['key','Clave'],['value','Valor'],['description','Descripción']],fields:[F('category','Categoría','text'),F('key','Clave','text',null,true),F('value','Valor','textarea',null,true),F('description','Descripción','text')]},
    audit:{title:'Auditoría',deletable:false,section:'ADMINISTRACIÓN',icon:'shield',endpoint:'/api/audit',permission:'audit.read',readOnly:true,columns:[['occurredAt','Fecha','datetime'],['userName','Usuario'],['module','Módulo'],['action','Acción'],['entityName','Entidad'],['entityId','ID'],['ipAddress','IP']]}
  }
};
function F(key,label,type='text',options=null,required=false){return{key,label,type,options,required}}
